// All remaining states from user's comprehensive 50-state list

const allRemainingStates = [
  // Delaware
  { name: "Wilmington", state: "DE", stateName: "Delaware", population: 70851 },
  { name: "Dover", state: "DE", stateName: "Delaware", population: 38079 },
  { name: "Newark", state: "DE", stateName: "Delaware", population: 31454 },
  { name: "Middletown", state: "DE", stateName: "Delaware", population: 22938 },
  { name: "Smyrna", state: "DE", stateName: "Delaware", population: 11480 },
  { name: "Milford", state: "DE", stateName: "Delaware", population: 11490 },
  { name: "Seaford", state: "DE", stateName: "Delaware", population: 7897 },
  { name: "Georgetown", state: "DE", stateName: "Delaware", population: 7074 },
  { name: "Lewes", state: "DE", stateName: "Delaware", population: 3277 },
  { name: "New Castle", state: "DE", stateName: "Delaware", population: 5285 },

  // Hawaii
  { name: "Honolulu", state: "HI", stateName: "Hawaii", population: 350964 },
  { name: "Pearl City", state: "HI", stateName: "Hawaii", population: 47698 },
  { name: "Hilo", state: "HI", stateName: "Hawaii", population: 43263 },
  { name: "Kailua", state: "HI", stateName: "Hawaii", population: 38256 },
  { name: "Kaneohe", state: "HI", stateName: "Hawaii", population: 34597 },
  { name: "Waipahu", state: "HI", stateName: "Hawaii", population: 43343 },
  { name: "Kailua-Kona", state: "HI", stateName: "Hawaii", population: 12000 },
  { name: "Kahului", state: "HI", stateName: "Hawaii", population: 26455 },
  { name: "Kihei", state: "HI", stateName: "Hawaii", population: 20801 },
  { name: "Lihue", state: "HI", stateName: "Hawaii", population: 6474 },
  { name: "Wailuku", state: "HI", stateName: "Hawaii", population: 15256 },
  { name: "Kapaa", state: "HI", stateName: "Hawaii", population: 10699 },
  { name: "Ewa Beach", state: "HI", stateName: "Hawaii", population: 15000 },
  { name: "Mililani", state: "HI", stateName: "Hawaii", population: 28000 },
  { name: "Kailua", state: "HI", stateName: "Hawaii", population: 38256 },
  { name: "Kaneohe", state: "HI", stateName: "Hawaii", population: 34597 },
  { name: "Waipahu", state: "HI", stateName: "Hawaii", population: 43343 },
  { name: "Kailua-Kona", state: "HI", stateName: "Hawaii", population: 12000 },
  { name: "Kahului", state: "HI", stateName: "Hawaii", population: 26455 },
  { name: "Kihei", state: "HI", stateName: "Hawaii", population: 20801 },
  { name: "Lihue", state: "HI", stateName: "Hawaii", population: 6474 },
  { name: "Wailuku", state: "HI", stateName: "Hawaii", population: 15256 },
  { name: "Kapaa", state: "HI", stateName: "Hawaii", population: 10699 },
  { name: "Ewa Beach", state: "HI", stateName: "Hawaii", population: 15000 },
  { name: "Mililani", state: "HI", stateName: "Hawaii", population: 28000 },
  { name: "Hanalei", state: "HI", stateName: "Hawaii", population: 450 },
  { name: "Honaunau", state: "HI", stateName: "Hawaii", population: 0 },
  { name: "Kawaihae", state: "HI", stateName: "Hawaii", population: 0 },
  { name: "Lahaina", state: "HI", stateName: "Hawaii", population: 0 },
  { name: "Laie", state: "HI", stateName: "Hawaii", population: 0 },
  { name: "Wahiawa", state: "HI", stateName: "Hawaii", population: 0 },
  { name: "Waimea", state: "HI", stateName: "Hawaii", population: 0 },

  // Idaho
  { name: "Boise", state: "ID", stateName: "Idaho", population: 228790 },
  { name: "Nampa", state: "ID", stateName: "Idaho", population: 100200 },
  { name: "Meridian", state: "ID", stateName: "Idaho", population: 117635 },
  { name: "Idaho Falls", state: "ID", stateName: "Idaho", population: 64718 },
  { name: "Pocatello", state: "ID", stateName: "Idaho", population: 56746 },
  { name: "Caldwell", state: "ID", stateName: "Idaho", population: 56747 },
  { name: "Coeur d'Alene", state: "ID", stateName: "Idaho", population: 55097 },
  { name: "Twin Falls", state: "ID", stateName: "Idaho", population: 51230 },
  { name: "Lewiston", state: "ID", stateName: "Idaho", population: 33606 },
  { name: "Post Falls", state: "ID", stateName: "Idaho", population: 38085 },
  { name: "Rexburg", state: "ID", stateName: "Idaho", population: 35832 },
  { name: "Eagle", state: "ID", stateName: "Idaho", population: 30037 },
  { name: "Chubbuck", state: "ID", stateName: "Idaho", population: 15268 },
  { name: "Ammon", state: "ID", stateName: "Idaho", population: 16331 },
  { name: "Hayden", state: "ID", stateName: "Idaho", population: 15070 },
  { name: "Mountain Home", state: "ID", stateName: "Idaho", population: 14324 },
  { name: "Kuna", state: "ID", stateName: "Idaho", population: 24011 },
  { name: "Moscow", state: "ID", stateName: "Idaho", population: 25035 },
  { name: "Garden City", state: "ID", stateName: "Idaho", population: 12039 },
  { name: "Emmett", state: "ID", stateName: "Idaho", population: 7077 },
  { name: "Rathdrum", state: "ID", stateName: "Idaho", population: 10081 },
  { name: "Blackfoot", state: "ID", stateName: "Idaho", population: 11936 },
  { name: "Sandpoint", state: "ID", stateName: "Idaho", population: 8765 },
  { name: "Jerome", state: "ID", stateName: "Idaho", population: 11469 },
  { name: "Payette", state: "ID", stateName: "Idaho", population: 7739 },
  { name: "Burley", state: "ID", stateName: "Idaho", population: 10409 },
  { name: "Preston", state: "ID", stateName: "Idaho", population: 5208 },
  { name: "Rigby", state: "ID", stateName: "Idaho", population: 4108 },
  { name: "Rupert", state: "ID", stateName: "Idaho", population: 5946 },
  { name: "Weiser", state: "ID", stateName: "Idaho", population: 5507 },
  { name: "Idaho City", state: "ID", stateName: "Idaho", population: 485 },
  { name: "Bonners Ferry", state: "ID", stateName: "Idaho", population: 2538 },
  { name: "Kellogg", state: "ID", stateName: "Idaho", population: 2080 },
  { name: "Priest River", state: "ID", stateName: "Idaho", population: 1747 },
  { name: "Sun Valley", state: "ID", stateName: "Idaho", population: 1406 },

  // Iowa
  { name: "Des Moines", state: "IA", stateName: "Iowa", population: 214133 },
  { name: "Cedar Rapids", state: "IA", stateName: "Iowa", population: 137710 },
  { name: "Davenport", state: "IA", stateName: "Iowa", population: 101724 },
  { name: "Sioux City", state: "IA", stateName: "Iowa", population: 82804 },
  { name: "Iowa City", state: "IA", stateName: "Iowa", population: 74828 },
  { name: "Waterloo", state: "IA", stateName: "Iowa", population: 67098 },
  { name: "Council Bluffs", state: "IA", stateName: "Iowa", population: 62166 },
  { name: "Ames", state: "IA", stateName: "Iowa", population: 66305 },
  { name: "West Des Moines", state: "IA", stateName: "Iowa", population: 68798 },
  { name: "Dubuque", state: "IA", stateName: "Iowa", population: 57937 },
  { name: "Ankeny", state: "IA", stateName: "Iowa", population: 67887 },
  { name: "Urbandale", state: "IA", stateName: "Iowa", population: 45080 },
  { name: "Cedar Falls", state: "IA", stateName: "Iowa", population: 40714 },
  { name: "Marion", state: "IA", stateName: "Iowa", population: 39922 },
  { name: "Bettendorf", state: "IA", stateName: "Iowa", population: 39002 },
  { name: "Mason City", state: "IA", stateName: "Iowa", population: 27074 },
  { name: "Marshalltown", state: "IA", stateName: "Iowa", population: 27091 },
  { name: "Clinton", state: "IA", stateName: "Iowa", population: 24855 },
  { name: "Burlington", state: "IA", stateName: "Iowa", population: 24530 },
  { name: "Ottumwa", state: "IA", stateName: "Iowa", population: 25023 },
  { name: "Fort Dodge", state: "IA", stateName: "Iowa", population: 24162 },
  { name: "Muscatine", state: "IA", stateName: "Iowa", population: 23968 },
  { name: "Coralville", state: "IA", stateName: "Iowa", population: 22018 },
  { name: "Johnston", state: "IA", stateName: "Iowa", population: 24064 },
  { name: "North Liberty", state: "IA", stateName: "Iowa", population: 20479 },
  { name: "Indianola", state: "IA", stateName: "Iowa", population: 15792 },
  { name: "Altoona", state: "IA", stateName: "Iowa", population: 19650 },
  { name: "Pella", state: "IA", stateName: "Iowa", population: 10591 },
  { name: "Newton", state: "IA", stateName: "Iowa", population: 15054 },
  { name: "Grinnell", state: "IA", stateName: "Iowa", population: 9143 },
  { name: "Amana Colonies", state: "IA", stateName: "Iowa", population: 0 },
  { name: "Boone", state: "IA", stateName: "Iowa", population: 12460 },
  { name: "Charles City", state: "IA", stateName: "Iowa", population: 7426 },
  { name: "Cherokee", state: "IA", stateName: "Iowa", population: 5049 },
  { name: "Estherville", state: "IA", stateName: "Iowa", population: 5994 },
  { name: "Fairfield", state: "IA", stateName: "Iowa", population: 10363 },
  { name: "Keokuk", state: "IA", stateName: "Iowa", population: 10078 },
  { name: "Mount Pleasant", state: "IA", stateName: "Iowa", population: 8751 },
  { name: "Oskaloosa", state: "IA", stateName: "Iowa", population: 11558 },
  { name: "Webster City", state: "IA", stateName: "Iowa", population: 7800 },

  // Kansas
  { name: "Wichita", state: "KS", stateName: "Kansas", population: 397532 },
  { name: "Overland Park", state: "KS", stateName: "Kansas", population: 197238 },
  { name: "Kansas City", state: "KS", stateName: "Kansas", population: 156607 },
  { name: "Olathe", state: "KS", stateName: "Kansas", population: 141290 },
  { name: "Topeka", state: "KS", stateName: "Kansas", population: 125310 },
  { name: "Lawrence", state: "KS", stateName: "Kansas", population: 94934 },
  { name: "Shawnee", state: "KS", stateName: "Kansas", population: 67105 },
  { name: "Manhattan", state: "KS", stateName: "Kansas", population: 54100 },
  { name: "Lenexa", state: "KS", stateName: "Kansas", population: 57140 },
  { name: "Salina", state: "KS", stateName: "Kansas", population: 46089 },
  { name: "Hutchinson", state: "KS", stateName: "Kansas", population: 40006 },
  { name: "Leavenworth", state: "KS", stateName: "Kansas", population: 37000 },
  { name: "Leawood", state: "KS", stateName: "Kansas", population: 35000 },
  { name: "Dodge City", state: "KS", stateName: "Kansas", population: 28075 },
  { name: "Garden City", state: "KS", stateName: "Kansas", population: 28000 },
  { name: "Emporia", state: "KS", stateName: "Kansas", population: 25000 },
  { name: "Derby", state: "KS", stateName: "Kansas", population: 25000 },
  { name: "Prairie Village", state: "KS", stateName: "Kansas", population: 22000 },
  { name: "Hays", state: "KS", stateName: "Kansas", population: 21000 },
  { name: "Pittsburg", state: "KS", stateName: "Kansas", population: 20000 },
  { name: "Liberal", state: "KS", stateName: "Kansas", population: 20000 },
  { name: "Newton", state: "KS", stateName: "Kansas", population: 19000 },
  { name: "Great Bend", state: "KS", stateName: "Kansas", population: 15000 },
  { name: "McPherson", state: "KS", stateName: "Kansas", population: 13000 },
  { name: "El Dorado", state: "KS", stateName: "Kansas", population: 13000 },
  { name: "Ottawa", state: "KS", stateName: "Kansas", population: 12000 },
  { name: "Arkansas City", state: "KS", stateName: "Kansas", population: 12000 },
  { name: "Atchison", state: "KS", stateName: "Kansas", population: 11000 },
  { name: "Chanute", state: "KS", stateName: "Kansas", population: 9000 },
  { name: "Coffeyville", state: "KS", stateName: "Kansas", population: 9000 },
  { name: "Council Grove", state: "KS", stateName: "Kansas", population: 2000 },
  { name: "Fort Scott", state: "KS", stateName: "Kansas", population: 8000 },
  { name: "Garden City", state: "KS", stateName: "Kansas", population: 28000 },
  { name: "Great Bend", state: "KS", stateName: "Kansas", population: 15000 },
  { name: "Hays", state: "KS", stateName: "Kansas", population: 21000 },
  { name: "Hutchinson", state: "KS", stateName: "Kansas", population: 40006 },
  { name: "Independence", state: "KS", stateName: "Kansas", population: 8000 },
  { name: "Junction City", state: "KS", stateName: "Kansas", population: 23000 },
  { name: "Kansas City", state: "KS", stateName: "Kansas", population: 156607 },
  { name: "Lawrence", state: "KS", stateName: "Kansas", population: 94934 },
  { name: "Leavenworth", state: "KS", stateName: "Kansas", population: 37000 },
  { name: "Leawood", state: "KS", stateName: "Kansas", population: 35000 },
  { name: "Lenexa", state: "KS", stateName: "Kansas", population: 57140 },
  { name: "Liberal", state: "KS", stateName: "Kansas", population: 20000 },
  { name: "Manhattan", state: "KS", stateName: "Kansas", population: 54100 },
  { name: "McPherson", state: "KS", stateName: "Kansas", population: 13000 },
  { name: "Newton", state: "KS", stateName: "Kansas", population: 19000 },
  { name: "Olathe", state: "KS", stateName: "Kansas", population: 141290 },
  { name: "Ottawa", state: "KS", stateName: "Kansas", population: 12000 },
  { name: "Overland Park", state: "KS", stateName: "Kansas", population: 197238 },
  { name: "Pittsburg", state: "KS", stateName: "Kansas", population: 20000 },
  { name: "Prairie Village", state: "KS", stateName: "Kansas", population: 22000 },
  { name: "Salina", state: "KS", stateName: "Kansas", population: 46089 },
  { name: "Shawnee", state: "KS", stateName: "Kansas", population: 67105 },
  { name: "Topeka", state: "KS", stateName: "Kansas", population: 125310 },
  { name: "Wichita", state: "KS", stateName: "Kansas", population: 397532 },
  { name: "Abilene", state: "KS", stateName: "Kansas", population: 6000 },
  { name: "Medicine Lodge", state: "KS", stateName: "Kansas", population: 2000 },
  { name: "Osawatomie", state: "KS", stateName: "Kansas", population: 4000 },
  { name: "Smith Center", state: "KS", stateName: "Kansas", population: 1000 },

  // Kentucky
  { name: "Louisville", state: "KY", stateName: "Kentucky", population: 617638 },
  { name: "Lexington", state: "KY", stateName: "Kentucky", population: 323780 },
  { name: "Bowling Green", state: "KY", stateName: "Kentucky", population: 72894 },
  { name: "Owensboro", state: "KY", stateName: "Kentucky", population: 60061 },
  { name: "Covington", state: "KY", stateName: "Kentucky", population: 40840 },
  { name: "Hopkinsville", state: "KY", stateName: "Kentucky", population: 31680 },
  { name: "Richmond", state: "KY", stateName: "Kentucky", population: 36604 },
  { name: "Florence", state: "KY", stateName: "Kentucky", population: 33198 },
  { name: "Georgetown", state: "KY", stateName: "Kentucky", population: 37517 },
  { name: "Henderson", state: "KY", stateName: "Kentucky", population: 28572 },
  { name: "Elizabethtown", state: "KY", stateName: "Kentucky", population: 31008 },
  { name: "Nicholasville", state: "KY", stateName: "Kentucky", population: 31000 },
  { name: "Jeffersontown", state: "KY", stateName: "Kentucky", population: 28000 },
  { name: "Frankfort", state: "KY", stateName: "Kentucky", population: 28000 },
  { name: "Paducah", state: "KY", stateName: "Kentucky", population: 25000 },
  { name: "Radcliff", state: "KY", stateName: "Kentucky", population: 23000 },
  { name: "Ashland", state: "KY", stateName: "Kentucky", population: 21000 },
  { name: "Madisonville", state: "KY", stateName: "Kentucky", population: 19000 },
  { name: "Murray", state: "KY", stateName: "Kentucky", population: 19000 },
  { name: "St. Matthews", state: "KY", stateName: "Kentucky", population: 18000 },
  { name: "Shively", state: "KY", stateName: "Kentucky", population: 15000 },
  { name: "Newport", state: "KY", stateName: "Kentucky", population: 15000 },
  { name: "Fort Thomas", state: "KY", stateName: "Kentucky", population: 16000 },
  { name: "Middlesboro", state: "KY", stateName: "Kentucky", population: 10000 },
  { name: "Mayfield", state: "KY", stateName: "Kentucky", population: 10000 },
  { name: "Maysville", state: "KY", stateName: "Kentucky", population: 9000 },
  { name: "Bardstown", state: "KY", stateName: "Kentucky", population: 12000 },
  { name: "Berea", state: "KY", stateName: "Kentucky", population: 15000 },
  { name: "Boonesborough", state: "KY", stateName: "Kentucky", population: 0 },
  { name: "Campbellsville", state: "KY", stateName: "Kentucky", population: 12000 },
  { name: "Danville", state: "KY", stateName: "Kentucky", population: 17000 },
  { name: "Harlan", state: "KY", stateName: "Kentucky", population: 1500 },
  { name: "Harrodsburg", state: "KY", stateName: "Kentucky", population: 9000 },
  { name: "Hazard", state: "KY", stateName: "Kentucky", population: 5000 },
  { name: "Hodgenville", state: "KY", stateName: "Kentucky", population: 3000 },
  { name: "Paris", state: "KY", stateName: "Kentucky", population: 10000 },
  { name: "Barbourville", state: "KY", stateName: "Kentucky", population: 3000 }
];

module.exports = allRemainingStates;
