// Critical missing states from user's original list

const criticalStates = [
  // Texas - Major cities from user's list
  { name: "Houston", state: "TX", stateName: "Texas", population: 2304580 },
  { name: "San Antonio", state: "TX", stateName: "Texas", population: 1547253 },
  { name: "Dallas", state: "TX", stateName: "Texas", population: 1343573 },
  { name: "Austin", state: "TX", stateName: "Texas", population: 978908 },
  { name: "Fort Worth", state: "TX", stateName: "Texas", population: 918915 },
  { name: "El Paso", state: "TX", stateName: "Texas", population: 678815 },
  { name: "Arlington", state: "TX", stateName: "Texas", population: 398112 },
  { name: "Corpus Christi", state: "TX", stateName: "Texas", population: 317863 },
  { name: "Plano", state: "TX", stateName: "Texas", population: 285494 },
  { name: "Lubbock", state: "TX", stateName: "Texas", population: 257141 },
  { name: "Laredo", state: "TX", stateName: "Texas", population: 255205 },
  { name: "Garland", state: "TX", stateName: "Texas", population: 246018 },
  { name: "Irving", state: "TX", stateName: "Texas", population: 256684 },
  { name: "Amarillo", state: "TX", stateName: "Texas", population: 200393 },
  { name: "Grand Prairie", state: "TX", stateName: "Texas", population: 196100 },
  { name: "Mesquite", state: "TX", stateName: "Texas", population: 150108 },
  { name: "McKinney", state: "TX", stateName: "Texas", population: 195308 },
  { name: "Killeen", state: "TX", stateName: "Texas", population: 153095 },
  { name: "Frisco", state: "TX", stateName: "Texas", population: 200509 },
  { name: "Waco", state: "TX", stateName: "Texas", population: 138486 },
  { name: "Carrollton", state: "TX", stateName: "Texas", population: 133434 },
  { name: "Denton", state: "TX", stateName: "Texas", population: 139869 },
  { name: "Midland", state: "TX", stateName: "Texas", population: 132524 },
  { name: "Abilene", state: "TX", stateName: "Texas", population: 125182 },
  { name: "Round Rock", state: "TX", stateName: "Texas", population: 119468 },
  { name: "Richardson", state: "TX", stateName: "Texas", population: 119469 },
  { name: "Odessa", state: "TX", stateName: "Texas", population: 119720 },
  { name: "Tyler", state: "TX", stateName: "Texas", population: 105995 },
  { name: "Lewisville", state: "TX", stateName: "Texas", population: 111822 },
  { name: "College Station", state: "TX", stateName: "Texas", population: 120511 },
  { name: "San Angelo", state: "TX", stateName: "Texas", population: 101612 },
  { name: "Pearland", state: "TX", stateName: "Texas", population: 125828 },
  { name: "Allen", state: "TX", stateName: "Texas", population: 104627 },
  { name: "Sugar Land", state: "TX", stateName: "Texas", population: 118488 },
  { name: "Longview", state: "TX", stateName: "Texas", population: 81522 },
  { name: "Edinburg", state: "TX", stateName: "Texas", population: 100243 },
  { name: "Mission", state: "TX", stateName: "Texas", population: 83741 },
  { name: "Bryan", state: "TX", stateName: "Texas", population: 86379 },
  { name: "Baytown", state: "TX", stateName: "Texas", population: 76635 },
  { name: "Pharr", state: "TX", stateName: "Texas", population: 79201 },
  { name: "Temple", state: "TX", stateName: "Texas", population: 82073 },
  { name: "Missouri City", state: "TX", stateName: "Texas", population: 74138 },
  { name: "Flower Mound", state: "TX", stateName: "Texas", population: 75056 },
  { name: "Harlingen", state: "TX", stateName: "Texas", population: 65660 },
  { name: "North Richland Hills", state: "TX", stateName: "Texas", population: 69517 },
  { name: "Victoria", state: "TX", stateName: "Texas", population: 67114 },
  { name: "Conroe", state: "TX", stateName: "Texas", population: 89856 },
  { name: "New Braunfels", state: "TX", stateName: "Texas", population: 90598 },
  { name: "Mansfield", state: "TX", stateName: "Texas", population: 72928 },
  { name: "Cedar Park", state: "TX", stateName: "Texas", population: 77179 },
  { name: "Rowlett", state: "TX", stateName: "Texas", population: 67922 },
  { name: "Port Arthur", state: "TX", stateName: "Texas", population: 56039 },
  { name: "Euless", state: "TX", stateName: "Texas", population: 61272 },
  { name: "Georgetown", state: "TX", stateName: "Texas", population: 75128 },
  { name: "Pflugerville", state: "TX", stateName: "Texas", population: 65604 },
  { name: "DeSoto", state: "TX", stateName: "Texas", population: 54145 },
  { name: "San Marcos", state: "TX", stateName: "Texas", population: 63674 },
  { name: "Grapevine", state: "TX", stateName: "Texas", population: 53958 },
  { name: "Bedford", state: "TX", stateName: "Texas", population: 49145 },
  { name: "Galveston", state: "TX", stateName: "Texas", population: 50099 },
  { name: "Cedar Hill", state: "TX", stateName: "Texas", population: 49148 },
  { name: "Texas City", state: "TX", stateName: "Texas", population: 48343 },
  { name: "Wylie", state: "TX", stateName: "Texas", population: 57197 },
  { name: "Haltom City", state: "TX", stateName: "Texas", population: 44100 },
  { name: "Keller", state: "TX", stateName: "Texas", population: 45866 },
  { name: "Coppell", state: "TX", stateName: "Texas", population: 42234 },
  { name: "Rockwall", state: "TX", stateName: "Texas", population: 47451 },
  { name: "Huntsville", state: "TX", stateName: "Texas", population: 45218 },
  { name: "Duncanville", state: "TX", stateName: "Texas", population: 40446 },
  { name: "Sherman", state: "TX", stateName: "Texas", population: 43335 },
  { name: "The Colony", state: "TX", stateName: "Texas", population: 44357 },
  { name: "Burleson", state: "TX", stateName: "Texas", population: 47393 },
  { name: "Hurst", state: "TX", stateName: "Texas", population: 38727 },
  { name: "Lancaster", state: "TX", stateName: "Texas", population: 41149 },
  { name: "Friendswood", state: "TX", stateName: "Texas", population: 39562 },
  { name: "Weslaco", state: "TX", stateName: "Texas", population: 40595 },
  { name: "Greenville", state: "TX", stateName: "Texas", population: 28464 },
  { name: "Nacogdoches", state: "TX", stateName: "Texas", population: 33347 },
  { name: "Kerrville", state: "TX", stateName: "Texas", population: 24347 },
  { name: "Paris", state: "TX", stateName: "Texas", population: 24870 },
  { name: "Del Rio", state: "TX", stateName: "Texas", population: 35891 },
  { name: "Eagle Pass", state: "TX", stateName: "Texas", population: 28625 },
  { name: "Brownsville", state: "TX", stateName: "Texas", population: 186738 },
  { name: "McAllen", state: "TX", stateName: "Texas", population: 142212 },
  { name: "Laredo", state: "TX", stateName: "Texas", population: 255205 },
  { name: "Harlingen", state: "TX", stateName: "Texas", population: 65660 },
  { name: "Edinburg", state: "TX", stateName: "Texas", population: 100243 },
  { name: "Mission", state: "TX", stateName: "Texas", population: 83741 },
  { name: "Pharr", state: "TX", stateName: "Texas", population: 79201 },
  { name: "Weslaco", state: "TX", stateName: "Texas", population: 40595 },
  { name: "Brownsville", state: "TX", stateName: "Texas", population: 186738 },
  { name: "McAllen", state: "TX", stateName: "Texas", population: 142212 },
  { name: "Laredo", state: "TX", stateName: "Texas", population: 255205 },
  { name: "Harlingen", state: "TX", stateName: "Texas", population: 65660 },
  { name: "Edinburg", state: "TX", stateName: "Texas", population: 100243 },
  { name: "Mission", state: "TX", stateName: "Texas", population: 83741 },
  { name: "Pharr", state: "TX", stateName: "Texas", population: 79201 },
  { name: "Weslaco", state: "TX", stateName: "Texas", population: 40595 },

  // Ohio - Major cities from user's list
  { name: "Columbus", state: "OH", stateName: "Ohio", population: 905748 },
  { name: "Cleveland", state: "OH", stateName: "Ohio", population: 383793 },
  { name: "Cincinnati", state: "OH", stateName: "Ohio", population: 309317 },
  { name: "Toledo", state: "OH", stateName: "Ohio", population: 270871 },
  { name: "Akron", state: "OH", stateName: "Ohio", population: 197597 },
  { name: "Dayton", state: "OH", stateName: "Ohio", population: 140407 },
  { name: "Parma", state: "OH", stateName: "Ohio", population: 81499 },
  { name: "Canton", state: "OH", stateName: "Ohio", population: 70408 },
  { name: "Youngstown", state: "OH", stateName: "Ohio", population: 64125 },
  { name: "Lorain", state: "OH", stateName: "Ohio", population: 63632 },
  { name: "Hamilton", state: "OH", stateName: "Ohio", population: 62231 },
  { name: "Springfield", state: "OH", stateName: "Ohio", population: 58808 },
  { name: "Kettering", state: "OH", stateName: "Ohio", population: 57653 },
  { name: "Elyria", state: "OH", stateName: "Ohio", population: 52899 },
  { name: "Lakewood", state: "OH", stateName: "Ohio", population: 50211 },
  { name: "Cuyahoga Falls", state: "OH", stateName: "Ohio", population: 49652 },
  { name: "Middletown", state: "OH", stateName: "Ohio", population: 48694 },
  { name: "Newark", state: "OH", stateName: "Ohio", population: 50778 },
  { name: "Mansfield", state: "OH", stateName: "Ohio", population: 46482 },
  { name: "Mentor", state: "OH", stateName: "Ohio", population: 47159 },
  { name: "Beavercreek", state: "OH", stateName: "Ohio", population: 46949 },
  { name: "Cleveland Heights", state: "OH", stateName: "Ohio", population: 45144 },
  { name: "Strongsville", state: "OH", stateName: "Ohio", population: 44750 },
  { name: "Fairborn", state: "OH", stateName: "Ohio", population: 33960 },
  { name: "Findlay", state: "OH", stateName: "Ohio", population: 41903 },
  { name: "Warren", state: "OH", stateName: "Ohio", population: 39403 },
  { name: "Lancaster", state: "OH", stateName: "Ohio", population: 40408 },
  { name: "Lima", state: "OH", stateName: "Ohio", population: 35601 },
  { name: "Huber Heights", state: "OH", stateName: "Ohio", population: 38751 },
  { name: "Westerville", state: "OH", stateName: "Ohio", population: 39009 },
  { name: "Marion", state: "OH", stateName: "Ohio", population: 35871 },
  { name: "Grove City", state: "OH", stateName: "Ohio", population: 41552 },
  { name: "Stow", state: "OH", stateName: "Ohio", population: 34510 },
  { name: "Delaware", state: "OH", stateName: "Ohio", population: 41801 },
  { name: "Bowling Green", state: "OH", stateName: "Ohio", population: 31845 },
  { name: "Massillon", state: "OH", stateName: "Ohio", population: 32406 },
  { name: "Upper Arlington", state: "OH", stateName: "Ohio", population: 36800 },
  { name: "Gahanna", state: "OH", stateName: "Ohio", population: 35551 },
  { name: "Worthington", state: "OH", stateName: "Ohio", population: 14926 },
  { name: "Reynoldsburg", state: "OH", stateName: "Ohio", population: 38781 },
  { name: "Pickerington", state: "OH", stateName: "Ohio", population: 23094 },
  { name: "Dublin", state: "OH", stateName: "Ohio", population: 49430 },
  { name: "Hilliard", state: "OH", stateName: "Ohio", population: 37099 },
  { name: "Groveport", state: "OH", stateName: "Ohio", population: 5756 },
  { name: "Bexley", state: "OH", stateName: "Ohio", population: 13928 },
  { name: "Whitehall", state: "OH", stateName: "Ohio", population: 18512 },
  { name: "Grandview Heights", state: "OH", stateName: "Ohio", population: 8310 },
  { name: "Valleyview", state: "OH", stateName: "Ohio", population: 616 },
  { name: "Marble Cliff", state: "OH", stateName: "Ohio", population: 565 },
  { name: "Brice", state: "OH", stateName: "Ohio", population: 114 },
  { name: "Urbancrest", state: "OH", stateName: "Ohio", population: 960 },
  { name: "Minerva Park", state: "OH", stateName: "Ohio", population: 1372 },
  { name: "Obetz", state: "OH", stateName: "Ohio", population: 5080 },
  { name: "Lockbourne", state: "OH", stateName: "Ohio", population: 237 },
  { name: "Canal Winchester", state: "OH", stateName: "Ohio", population: 9147 },
  { name: "Lithopolis", state: "OH", stateName: "Ohio", population: 1155 },
  { name: "Ashville", state: "OH", stateName: "Ohio", population: 4040 },
  { name: "South Bloomfield", state: "OH", stateName: "Ohio", population: 2051 },
  { name: "Commercial Point", state: "OH", stateName: "Ohio", population: 1672 },
  { name: "Grove City", state: "OH", stateName: "Ohio", population: 41552 },
  { name: "Columbus", state: "OH", stateName: "Ohio", population: 905748 },
  { name: "Upper Arlington", state: "OH", stateName: "Ohio", population: 36800 },
  { name: "Worthington", state: "OH", stateName: "Ohio", population: 14926 },
  { name: "Reynoldsburg", state: "OH", stateName: "Ohio", population: 38781 },
  { name: "Pickerington", state: "OH", stateName: "Ohio", population: 23094 },
  { name: "Dublin", state: "OH", stateName: "Ohio", population: 49430 },
  { name: "Hilliard", state: "OH", stateName: "Ohio", population: 37099 },
  { name: "Groveport", state: "OH", stateName: "Ohio", population: 5756 },
  { name: "Bexley", state: "OH", stateName: "Ohio", population: 13928 },
  { name: "Whitehall", state: "OH", stateName: "Ohio", population: 18512 },
  { name: "Grandview Heights", state: "OH", stateName: "Ohio", population: 8310 },
  { name: "Valleyview", state: "OH", stateName: "Ohio", population: 616 },
  { name: "Marble Cliff", state: "OH", stateName: "Ohio", population: 565 },
  { name: "Brice", state: "OH", stateName: "Ohio", population: 114 },
  { name: "Urbancrest", state: "OH", stateName: "Ohio", population: 960 },
  { name: "Minerva Park", state: "OH", stateName: "Ohio", population: 1372 },
  { name: "Obetz", state: "OH", stateName: "Ohio", population: 5080 },
  { name: "Lockbourne", state: "OH", stateName: "Ohio", population: 237 },
  { name: "Canal Winchester", state: "OH", stateName: "Ohio", population: 9147 },
  { name: "Lithopolis", state: "OH", stateName: "Ohio", population: 1155 },
  { name: "Ashville", state: "OH", stateName: "Ohio", population: 4040 },
  { name: "South Bloomfield", state: "OH", stateName: "Ohio", population: 2051 },
  { name: "Commercial Point", state: "OH", stateName: "Ohio", population: 1672 },

  // Pennsylvania - Major cities from user's list
  { name: "Philadelphia", state: "PA", stateName: "Pennsylvania", population: 1584064 },
  { name: "Pittsburgh", state: "PA", stateName: "Pennsylvania", population: 302971 },
  { name: "Allentown", state: "PA", stateName: "Pennsylvania", population: 125845 },
  { name: "Erie", state: "PA", stateName: "Pennsylvania", population: 94966 },
  { name: "Reading", state: "PA", stateName: "Pennsylvania", population: 95092 },
  { name: "Scranton", state: "PA", stateName: "Pennsylvania", population: 76908 },
  { name: "Bethlehem", state: "PA", stateName: "Pennsylvania", population: 75849 },
  { name: "Lancaster", state: "PA", stateName: "Pennsylvania", population: 59322 },
  { name: "Harrisburg", state: "PA", stateName: "Pennsylvania", population: 50135 },
  { name: "Altoona", state: "PA", stateName: "Pennsylvania", population: 43493 },
  { name: "York", state: "PA", stateName: "Pennsylvania", population: 44294 },
  { name: "State College", state: "PA", stateName: "Pennsylvania", population: 42034 },
  { name: "Wilkes-Barre", state: "PA", stateName: "Pennsylvania", population: 40806 },
  { name: "Chester", state: "PA", stateName: "Pennsylvania", population: 34056 },
  { name: "Williamsport", state: "PA", stateName: "Pennsylvania", population: 28437 },
  { name: "Easton", state: "PA", stateName: "Pennsylvania", population: 27216 },
  { name: "Lebanon", state: "PA", stateName: "Pennsylvania", population: 25892 },
  { name: "Hazleton", state: "PA", stateName: "Pennsylvania", population: 25031 },
  { name: "New Castle", state: "PA", stateName: "Pennsylvania", population: 22076 },
  { name: "Johnstown", state: "PA", stateName: "Pennsylvania", population: 19220 },
  { name: "Washington", state: "PA", stateName: "Pennsylvania", population: 13417 },
  { name: "Beaver Falls", state: "PA", stateName: "Pennsylvania", population: 8987 },
  { name: "Greensburg", state: "PA", stateName: "Pennsylvania", population: 14043 },
  { name: "Meadville", state: "PA", stateName: "Pennsylvania", population: 13134 },
  { name: "New Kensington", state: "PA", stateName: "Pennsylvania", population: 12984 },
  { name: "Butler", state: "PA", stateName: "Pennsylvania", population: 13115 },
  { name: "Uniontown", state: "PA", stateName: "Pennsylvania", population: 10108 },
  { name: "Monroeville", state: "PA", stateName: "Pennsylvania", population: 28386 },
  { name: "Plum", state: "PA", stateName: "Pennsylvania", population: 27200 },
  { name: "Shaler", state: "PA", stateName: "Pennsylvania", population: 28657 },
  { name: "Upper St. Clair", state: "PA", stateName: "Pennsylvania", population: 20220 },
  { name: "Peters", state: "PA", stateName: "Pennsylvania", population: 21764 },
  { name: "Mt. Lebanon", state: "PA", stateName: "Pennsylvania", population: 33275 },
  { name: "Bethel Park", state: "PA", stateName: "Pennsylvania", population: 32267 },
  { name: "Baldwin", state: "PA", stateName: "Pennsylvania", population: 19967 },
  { name: "Whitehall", state: "PA", stateName: "Pennsylvania", population: 13844 },
  { name: "West Mifflin", state: "PA", stateName: "Pennsylvania", population: 19739 },
  { name: "McKeesport", state: "PA", stateName: "Pennsylvania", population: 19117 },
  { name: "Penn Hills", state: "PA", stateName: "Pennsylvania", population: 41704 },
  { name: "Wilkinsburg", state: "PA", stateName: "Pennsylvania", population: 15232 },
  { name: "Forest Hills", state: "PA", stateName: "Pennsylvania", population: 6512 },
  { name: "Swissvale", state: "PA", stateName: "Pennsylvania", population: 8406 },
  { name: "Homestead", state: "PA", stateName: "Pennsylvania", population: 3108 },
  { name: "Munhall", state: "PA", stateName: "Pennsylvania", population: 11006 },
  { name: "Dravosburg", state: "PA", stateName: "Pennsylvania", population: 1759 },
  { name: "Glassport", state: "PA", stateName: "Pennsylvania", population: 4343 },
  { name: "Port Vue", state: "PA", stateName: "Pennsylvania", population: 3766 },
  { name: "Versailles", state: "PA", stateName: "Pennsylvania", population: 1529 },
  { name: "White Oak", state: "PA", stateName: "Pennsylvania", population: 7777 },
  { name: "North Versailles", state: "PA", stateName: "Pennsylvania", population: 10229 },
  { name: "East McKeesport", state: "PA", stateName: "Pennsylvania", population: 1886 },
  { name: "Wall", state: "PA", stateName: "Pennsylvania", population: 580 },
  { name: "Wilmerding", state: "PA", stateName: "Pennsylvania", population: 2131 },
  { name: "Turtle Creek", state: "PA", stateName: "Pennsylvania", population: 5343 },
  { name: "Braddock", state: "PA", stateName: "Pennsylvania", population: 2020 },
  { name: "Rankin", state: "PA", stateName: "Pennsylvania", population: 2100 },
  { name: "Swissvale", state: "PA", stateName: "Pennsylvania", population: 8406 },
  { name: "Edgewood", state: "PA", stateName: "Pennsylvania", population: 3113 },
  { name: "Churchill", state: "PA", stateName: "Pennsylvania", population: 3003 },
  { name: "Forest Hills", state: "PA", stateName: "Pennsylvania", population: 6512 },
  { name: "Wilkinsburg", state: "PA", stateName: "Pennsylvania", population: 15232 },
  { name: "Penn Hills", state: "PA", stateName: "Pennsylvania", population: 41704 },
  { name: "Plum", state: "PA", stateName: "Pennsylvania", population: 27200 },
  { name: "Monroeville", state: "PA", stateName: "Pennsylvania", population: 28386 },
  { name: "Shaler", state: "PA", stateName: "Pennsylvania", population: 28657 },
  { name: "Upper St. Clair", state: "PA", stateName: "Pennsylvania", population: 20220 },
  { name: "Peters", state: "PA", stateName: "Pennsylvania", population: 21764 },
  { name: "Mt. Lebanon", state: "PA", stateName: "Pennsylvania", population: 33275 },
  { name: "Bethel Park", state: "PA", stateName: "Pennsylvania", population: 32267 },
  { name: "Baldwin", state: "PA", stateName: "Pennsylvania", population: 19967 },
  { name: "Whitehall", state: "PA", stateName: "Pennsylvania", population: 13844 },
  { name: "West Mifflin", state: "PA", stateName: "Pennsylvania", population: 19739 },
  { name: "McKeesport", state: "PA", stateName: "Pennsylvania", population: 19117 },
  { name: "Penn Hills", state: "PA", stateName: "Pennsylvania", population: 41704 },
  { name: "Wilkinsburg", state: "PA", stateName: "Pennsylvania", population: 15232 },
  { name: "Forest Hills", state: "PA", stateName: "Pennsylvania", population: 6512 },
  { name: "Swissvale", state: "PA", stateName: "Pennsylvania", population: 8406 },
  { name: "Homestead", state: "PA", stateName: "Pennsylvania", population: 3108 },
  { name: "Munhall", state: "PA", stateName: "Pennsylvania", population: 11006 },
  { name: "Dravosburg", state: "PA", stateName: "Pennsylvania", population: 1759 },
  { name: "Glassport", state: "PA", stateName: "Pennsylvania", population: 4343 },
  { name: "Port Vue", state: "PA", stateName: "Pennsylvania", population: 3766 },
  { name: "Versailles", state: "PA", stateName: "Pennsylvania", population: 1529 },
  { name: "White Oak", state: "PA", stateName: "Pennsylvania", population: 7777 },
  { name: "North Versailles", state: "PA", stateName: "Pennsylvania", population: 10229 },
  { name: "East McKeesport", state: "PA", stateName: "Pennsylvania", population: 1886 },
  { name: "Wall", state: "PA", stateName: "Pennsylvania", population: 580 },
  { name: "Wilmerding", state: "PA", stateName: "Pennsylvania", population: 2131 },
  { name: "Turtle Creek", state: "PA", stateName: "Pennsylvania", population: 5343 },
  { name: "Braddock", state: "PA", stateName: "Pennsylvania", population: 2020 },
  { name: "Rankin", state: "PA", stateName: "Pennsylvania", population: 2100 },
  { name: "Swissvale", state: "PA", stateName: "Pennsylvania", population: 8406 },
  { name: "Edgewood", state: "PA", stateName: "Pennsylvania", population: 3113 },
  { name: "Churchill", state: "PA", stateName: "Pennsylvania", population: 3003 },
  { name: "Forest Hills", state: "PA", stateName: "Pennsylvania", population: 6512 },
  { name: "Wilkinsburg", state: "PA", stateName: "Pennsylvania", population: 15232 },
  { name: "Penn Hills", state: "PA", stateName: "Pennsylvania", population: 41704 }
];

module.exports = criticalStates;

