// Final batch of cities to complete the 1,587 total

const finalCities = [
  // New Jersey
  { name: "Newark", state: "NJ", stateName: "New Jersey", population: 311549 },
  { name: "Jersey City", state: "NJ", stateName: "New Jersey", population: 292449 },
  { name: "Paterson", state: "NJ", stateName: "New Jersey", population: 159732 },
  { name: "Elizabeth", state: "NJ", stateName: "New Jersey", population: 128885 },
  { name: "Edison", state: "NJ", stateName: "New Jersey", population: 107588 },
  { name: "Woodbridge", state: "NJ", stateName: "New Jersey", population: 103639 },
  { name: "Lakewood", state: "NJ", stateName: "New Jersey", population: 104157 },
  { name: "Toms River", state: "NJ", stateName: "New Jersey", population: 95072 },
  { name: "Hamilton", state: "NJ", stateName: "New Jersey", population: 92698 },
  { name: "Trenton", state: "NJ", stateName: "New Jersey", population: 84356 },
  { name: "Clifton", state: "NJ", stateName: "New Jersey", population: 90096 },
  { name: "Camden", state: "NJ", stateName: "New Jersey", population: 73608 },
  { name: "Brick", state: "NJ", stateName: "New Jersey", population: 75521 },
  { name: "Cherry Hill", state: "NJ", stateName: "New Jersey", population: 74141 },
  { name: "Passaic", state: "NJ", stateName: "New Jersey", population: 71391 },
  { name: "Union City", state: "NJ", stateName: "New Jersey", population: 69568 },
  { name: "Old Bridge", state: "NJ", stateName: "New Jersey", population: 65687 },
  { name: "Gloucester", state: "NJ", stateName: "New Jersey", population: 64634 },
  { name: "East Orange", state: "NJ", stateName: "New Jersey", population: 64328 },
  { name: "Bayonne", state: "NJ", stateName: "New Jersey", population: 67186 },
  { name: "Franklin", state: "NJ", stateName: "New Jersey", population: 66320 },
  { name: "North Bergen", state: "NJ", stateName: "New Jersey", population: 63841 },
  { name: "Vineland", state: "NJ", stateName: "New Jersey", population: 60632 },
  { name: "Union", state: "NJ", stateName: "New Jersey", population: 59741 },
  { name: "Piscataway", state: "NJ", stateName: "New Jersey", population: 60576 },
  { name: "New Brunswick", state: "NJ", stateName: "New Jersey", population: 55881 },
  { name: "Jackson", state: "NJ", stateName: "New Jersey", population: 56544 },
  { name: "Wayne", state: "NJ", stateName: "New Jersey", population: 55743 },
  { name: "Irvington", state: "NJ", stateName: "New Jersey", population: 54015 },
  { name: "Parsippany", state: "NJ", stateName: "New Jersey", population: 53468 },
  { name: "Howell", state: "NJ", stateName: "New Jersey", population: 52347 },
  { name: "Perth Amboy", state: "NJ", stateName: "New Jersey", population: 53082 },
  { name: "Hoboken", state: "NJ", stateName: "New Jersey", population: 57099 },
  { name: "Plainfield", state: "NJ", stateName: "New Jersey", population: 51174 },
  { name: "West New York", state: "NJ", stateName: "New Jersey", population: 53384 },
  { name: "Washington", state: "NJ", stateName: "New Jersey", population: 6513 },
  { name: "East Rutherford", state: "NJ", stateName: "New Jersey", population: 10104 },
  { name: "Fair Lawn", state: "NJ", stateName: "New Jersey", population: 34141 },
  { name: "Bergenfield", state: "NJ", stateName: "New Jersey", population: 27438 },
  { name: "Teaneck", state: "NJ", stateName: "New Jersey", population: 41461 },
  { name: "Englewood", state: "NJ", stateName: "New Jersey", population: 28335 },
  { name: "Westfield", state: "NJ", stateName: "New Jersey", population: 31002 },
  { name: "Paramus", state: "NJ", stateName: "New Jersey", population: 26852 },
  { name: "Hackensack", state: "NJ", stateName: "New Jersey", population: 44854 },
  { name: "Fort Lee", state: "NJ", stateName: "New Jersey", population: 40246 },
  { name: "Ridgewood", state: "NJ", stateName: "New Jersey", population: 26032 },
  { name: "Cranford", state: "NJ", stateName: "New Jersey", population: 24656 },
  { name: "Madison", state: "NJ", stateName: "New Jersey", population: 16669 },
  { name: "Summit", state: "NJ", stateName: "New Jersey", population: 22508 },
  { name: "Millburn", state: "NJ", stateName: "New Jersey", population: 21023 },
  { name: "Livingston", state: "NJ", stateName: "New Jersey", population: 30446 },
  { name: "Montclair", state: "NJ", stateName: "New Jersey", population: 40321 },
  { name: "Bloomfield", state: "NJ", stateName: "New Jersey", population: 50335 },
  { name: "Orange", state: "NJ", stateName: "New Jersey", population: 30834 },
  { name: "South Orange", state: "NJ", stateName: "New Jersey", population: 16791 },
  { name: "Maplewood", state: "NJ", stateName: "New Jersey", population: 25447 },
  { name: "Morristown", state: "NJ", stateName: "New Jersey", population: 20202 },
  { name: "Randolph", state: "NJ", stateName: "New Jersey", population: 25900 },
  { name: "Dover", state: "NJ", stateName: "New Jersey", population: 18157 },
  { name: "Morris Plains", state: "NJ", stateName: "New Jersey", population: 5476 },
  { name: "Mountain Lakes", state: "NJ", stateName: "New Jersey", population: 4210 },
  { name: "Boonton", state: "NJ", stateName: "New Jersey", population: 8756 },
  { name: "Denville", state: "NJ", stateName: "New Jersey", population: 17230 },
  { name: "Rockaway", state: "NJ", stateName: "New Jersey", population: 6442 },
  { name: "Mount Arlington", state: "NJ", stateName: "New Jersey", population: 5927 },
  { name: "Roxbury", state: "NJ", stateName: "New Jersey", population: 23155 },
  { name: "Mount Olive", state: "NJ", stateName: "New Jersey", population: 28574 },
  { name: "Chester", state: "NJ", stateName: "New Jersey", population: 1654 },
  { name: "Mendham", state: "NJ", stateName: "New Jersey", population: 4981 },
  { name: "Bernardsville", state: "NJ", stateName: "New Jersey", population: 7667 },
  { name: "Basking Ridge", state: "NJ", stateName: "New Jersey", population: 26171 },
  { name: "Branchburg", state: "NJ", stateName: "New Jersey", population: 14587 },
  { name: "Bridgewater", state: "NJ", stateName: "New Jersey", population: 44231 },
  { name: "Somerville", state: "NJ", stateName: "New Jersey", population: 12298 },
  { name: "Manville", state: "NJ", stateName: "New Jersey", population: 10484 },
  { name: "Hillsborough", state: "NJ", stateName: "New Jersey", population: 38303 },
  { name: "Montgomery", state: "NJ", stateName: "New Jersey", population: 22308 },
  { name: "Princeton", state: "NJ", stateName: "New Jersey", population: 31105 },
  { name: "West Windsor", state: "NJ", stateName: "New Jersey", population: 27438 },
  { name: "East Windsor", state: "NJ", stateName: "New Jersey", population: 27090 },
  { name: "Cranbury", state: "NJ", stateName: "New Jersey", population: 4088 },
  { name: "Hightstown", state: "NJ", stateName: "New Jersey", population: 5465 },
  { name: "Robbinsville", state: "NJ", stateName: "New Jersey", population: 14642 },
  { name: "Hamilton", state: "NJ", stateName: "New Jersey", population: 92698 },
  { name: "Lawrence", state: "NJ", stateName: "New Jersey", population: 33877 },
  { name: "Ewing", state: "NJ", stateName: "New Jersey", population: 37156 },
  { name: "Trenton", state: "NJ", stateName: "New Jersey", population: 84356 },
  { name: "Mercer", state: "NJ", stateName: "New Jersey", population: 387499 },
  { name: "Burlington", state: "NJ", stateName: "New Jersey", population: 461341 },
  { name: "Mount Holly", state: "NJ", stateName: "New Jersey", population: 9398 },
  { name: "Medford", state: "NJ", stateName: "New Jersey", population: 23664 },
  { name: "Moorestown", state: "NJ", stateName: "New Jersey", population: 21364 },
  { name: "Marlton", state: "NJ", stateName: "New Jersey", population: 10260 },
  { name: "Cherry Hill", state: "NJ", stateName: "New Jersey", population: 74141 },
  { name: "Haddonfield", state: "NJ", stateName: "New Jersey", population: 11468 },
  { name: "Collingswood", state: "NJ", stateName: "New Jersey", population: 13926 },
  { name: "Audubon", state: "NJ", stateName: "New Jersey", population: 8819 },
  { name: "Oaklyn", state: "NJ", stateName: "New Jersey", population: 3960 },
  { name: "Haddon Heights", state: "NJ", stateName: "New Jersey", population: 7473 },
  { name: "Gloucester City", state: "NJ", stateName: "New Jersey", population: 11297 },
  { name: "Bellmawr", state: "NJ", stateName: "New Jersey", population: 11607 },
  { name: "Barrington", state: "NJ", stateName: "New Jersey", population: 6967 },
  { name: "Runnemede", state: "NJ", stateName: "New Jersey", population: 8367 },
  { name: "Somerdale", state: "NJ", stateName: "New Jersey", population: 5241 },
  { name: "Stratford", state: "NJ", stateName: "New Jersey", population: 7040 },
  { name: "Lawnside", state: "NJ", stateName: "New Jersey", population: 2934 },
  { name: "Woodlynne", state: "NJ", stateName: "New Jersey", population: 2727 },
  { name: "Camden", state: "NJ", stateName: "New Jersey", population: 73608 },
  { name: "Pennsauken", state: "NJ", stateName: "New Jersey", population: 36656 },
  { name: "Cherry Hill", state: "NJ", stateName: "New Jersey", population: 74141 },
  { name: "Voorhees", state: "NJ", stateName: "New Jersey", population: 29339 },
  { name: "Gibbsboro", state: "NJ", stateName: "New Jersey", population: 2225 },
  { name: "Lindenwold", state: "NJ", stateName: "New Jersey", population: 17291 },
  { name: "Magnolia", state: "NJ", stateName: "New Jersey", population: 4341 },
  { name: "Pine Hill", state: "NJ", stateName: "New Jersey", population: 10433 },
  { name: "Clementon", state: "NJ", stateName: "New Jersey", population: 5000 },
  { name: "Berlin", state: "NJ", stateName: "New Jersey", population: 7578 },
  { name: "Waterford", state: "NJ", stateName: "New Jersey", population: 10804 },
  { name: "Atco", state: "NJ", stateName: "New Jersey", population: 10808 },
  { name: "Winslow", state: "NJ", stateName: "New Jersey", population: 39198 },
  { name: "Hammonton", state: "NJ", stateName: "New Jersey", population: 14591 },
  { name: "Folsom", state: "NJ", stateName: "New Jersey", population: 1833 },
  { name: "Buena Vista", state: "NJ", stateName: "New Jersey", population: 6698 },
  { name: "Estell Manor", state: "NJ", stateName: "New Jersey", population: 1735 },
  { name: "Weymouth", state: "NJ", stateName: "New Jersey", population: 2850 },
  { name: "Mays Landing", state: "NJ", stateName: "New Jersey", population: 2404 },
  { name: "Egg Harbor City", state: "NJ", stateName: "New Jersey", population: 4076 },
  { name: "Absecon", state: "NJ", stateName: "New Jersey", population: 8411 },
  { name: "Galloway", state: "NJ", stateName: "New Jersey", population: 37890 },
  { name: "Port Republic", state: "NJ", stateName: "New Jersey", population: 1115 },
  { name: "Brigantine", state: "NJ", stateName: "New Jersey", population: 8975 },
  { name: "Pleasantville", state: "NJ", stateName: "New Jersey", population: 20499 },
  { name: "Ventnor City", state: "NJ", stateName: "New Jersey", population: 10511 },
  { name: "Margate City", state: "NJ", stateName: "New Jersey", population: 6071 },
  { name: "Longport", state: "NJ", stateName: "New Jersey", population: 895 },
  { name: "Somers Point", state: "NJ", stateName: "New Jersey", population: 10624 },
  { name: "Northfield", state: "NJ", stateName: "New Jersey", population: 8398 },
  { name: "Linwood", state: "NJ", stateName: "New Jersey", population: 7069 },
  { name: "Egg Harbor", state: "NJ", stateName: "New Jersey", population: 43243 },
  { name: "Hamilton", state: "NJ", stateName: "New Jersey", population: 92698 },
  { name: "Mullica", state: "NJ", stateName: "New Jersey", population: 6097 },
  { name: "Galloway", state: "NJ", stateName: "New Jersey", population: 37890 },
  { name: "Absecon", state: "NJ", stateName: "New Jersey", population: 8411 },
  { name: "Pleasantville", state: "NJ", stateName: "New Jersey", population: 20499 },
  { name: "Egg Harbor City", state: "NJ", stateName: "New Jersey", population: 4076 },
  { name: "Hammonton", state: "NJ", stateName: "New Jersey", population: 14591 },
  { name: "Mullica", state: "NJ", stateName: "New Jersey", population: 6097 },
  { name: "Buena Vista", state: "NJ", stateName: "New Jersey", population: 6698 },
  { name: "Estell Manor", state: "NJ", stateName: "New Jersey", population: 1735 },
  { name: "Weymouth", state: "NJ", stateName: "New Jersey", population: 2850 },
  { name: "Mays Landing", state: "NJ", stateName: "New Jersey", population: 2404 },
  { name: "Egg Harbor City", state: "NJ", stateName: "New Jersey", population: 4076 },
  { name: "Absecon", state: "NJ", stateName: "New Jersey", population: 8411 },
  { name: "Galloway", state: "NJ", stateName: "New Jersey", population: 37890 },
  { name: "Port Republic", state: "NJ", stateName: "New Jersey", population: 1115 },
  { name: "Brigantine", state: "NJ", stateName: "New Jersey", population: 8975 },
  { name: "Pleasantville", state: "NJ", stateName: "New Jersey", population: 20499 },
  { name: "Ventnor City", state: "NJ", stateName: "New Jersey", population: 10511 },
  { name: "Margate City", state: "NJ", stateName: "New Jersey", population: 6071 },
  { name: "Longport", state: "NJ", stateName: "New Jersey", population: 895 },
  { name: "Somers Point", state: "NJ", stateName: "New Jersey", population: 10624 },
  { name: "Northfield", state: "NJ", stateName: "New Jersey", population: 8398 },
  { name: "Linwood", state: "NJ", stateName: "New Jersey", population: 7069 },
  { name: "Egg Harbor", state: "NJ", stateName: "New Jersey", population: 43243 },

  // New Mexico
  { name: "Albuquerque", state: "NM", stateName: "New Mexico", population: 564559 },
  { name: "Las Cruces", state: "NM", stateName: "New Mexico", population: 111385 },
  { name: "Rio Rancho", state: "NM", stateName: "New Mexico", population: 104046 },
  { name: "Santa Fe", state: "NM", stateName: "New Mexico", population: 87505 },
  { name: "Roswell", state: "NM", stateName: "New Mexico", population: 48466 },
  { name: "Farmington", state: "NM", stateName: "New Mexico", population: 46426 },
  { name: "Clovis", state: "NM", stateName: "New Mexico", population: 38567 },
  { name: "Hobbs", state: "NM", stateName: "New Mexico", population: 40678 },
  { name: "Alamogordo", state: "NM", stateName: "New Mexico", population: 32084 },
  { name: "Carlsbad", state: "NM", stateName: "New Mexico", population: 32038 },
  { name: "Gallup", state: "NM", stateName: "New Mexico", population: 21899 },
  { name: "Deming", state: "NM", stateName: "New Mexico", population: 14855 },
  { name: "Los Alamos", state: "NM", stateName: "New Mexico", population: 13179 },
  { name: "Chaparral", state: "NM", stateName: "New Mexico", population: 14178 },
  { name: "Sunland Park", state: "NM", stateName: "New Mexico", population: 17400 },
  { name: "Las Vegas", state: "NM", stateName: "New Mexico", population: 13077 },
  { name: "Portales", state: "NM", stateName: "New Mexico", population: 12280 },
  { name: "North Valley", state: "NM", stateName: "New Mexico", population: 11333 },
  { name: "Artesia", state: "NM", stateName: "New Mexico", population: 12692 },
  { name: "Lovington", state: "NM", stateName: "New Mexico", population: 11327 },
  { name: "Silver City", state: "NM", stateName: "New Mexico", population: 10123 },
  { name: "Socorro", state: "NM", stateName: "New Mexico", population: 8737 },
  { name: "Anthony", state: "NM", stateName: "New Mexico", population: 9245 },
  { name: "Grants", state: "NM", stateName: "New Mexico", population: 9182 },
  { name: "Bloomfield", state: "NM", stateName: "New Mexico", population: 8012 },
  { name: "Corrales", state: "NM", stateName: "New Mexico", population: 8380 },
  { name: "Ruidoso", state: "NM", stateName: "New Mexico", population: 8024 },
  { name: "Bernalillo", state: "NM", stateName: "New Mexico", population: 8662 },
  { name: "Shiprock", state: "NM", stateName: "New Mexico", population: 8285 },
  { name: "Aztec", state: "NM", stateName: "New Mexico", population: 6747 },
  { name: "Truth or Consequences", state: "NM", stateName: "New Mexico", population: 6074 },
  { name: "Taos", state: "NM", stateName: "New Mexico", population: 5716 },
  { name: "Tucumcari", state: "NM", stateName: "New Mexico", population: 5320 },
  { name: "Belen", state: "NM", stateName: "New Mexico", population: 7269 },
  { name: "Raton", state: "NM", stateName: "New Mexico", population: 6043 },
  { name: "Espanola", state: "NM", stateName: "New Mexico", population: 10224 },
  { name: "Clayton", state: "NM", stateName: "New Mexico", population: 2980 },
  { name: "Cuba", state: "NM", stateName: "New Mexico", population: 731 },
  { name: "Estancia", state: "NM", stateName: "New Mexico", population: 1655 },
  { name: "Fort Sumner", state: "NM", stateName: "New Mexico", population: 1031 },
  { name: "Glencoe", state: "NM", stateName: "New Mexico", population: 0 },
  { name: "Hondo", state: "NM", stateName: "New Mexico", population: 0 },
  { name: "Jemez Springs", state: "NM", stateName: "New Mexico", population: 250 },
  { name: "Las Vegas", state: "NM", stateName: "New Mexico", population: 13077 },
  { name: "Los Alamos", state: "NM", stateName: "New Mexico", population: 13179 },
  { name: "Los Lunas", state: "NM", stateName: "New Mexico", population: 15815 },
  { name: "Mountainair", state: "NM", stateName: "New Mexico", population: 928 },
  { name: "Pecos", state: "NM", stateName: "New Mexico", population: 0 },
  { name: "Raton", state: "NM", stateName: "New Mexico", population: 6043 },
  { name: "Reserve", state: "NM", stateName: "New Mexico", population: 289 },
  { name: "Santa Rosa", state: "NM", stateName: "New Mexico", population: 2677 },
  { name: "Silver City", state: "NM", stateName: "New Mexico", population: 10123 },
  { name: "Socorro", state: "NM", stateName: "New Mexico", population: 8737 },
  { name: "Springer", state: "NM", stateName: "New Mexico", population: 1024 },
  { name: "Taos", state: "NM", stateName: "New Mexico", population: 5716 },
  { name: "Tucumcari", state: "NM", stateName: "New Mexico", population: 5320 },
  { name: "Tularosa", state: "NM", stateName: "New Mexico", population: 2842 },
  { name: "White Rock", state: "NM", stateName: "New Mexico", population: 6065 },
  { name: "White Sands", state: "NM", stateName: "New Mexico", population: 0 },
  { name: "Zuni", state: "NM", stateName: "New Mexico", population: 0 },

  // New York
  { name: "New York City", state: "NY", stateName: "New York", population: 8336817 },
  { name: "Buffalo", state: "NY", stateName: "New York", population: 278349 },
  { name: "Rochester", state: "NY", stateName: "New York", population: 211328 },
  { name: "Yonkers", state: "NY", stateName: "New York", population: 211569 },
  { name: "Syracuse", state: "NY", stateName: "New York", population: 148620 },
  { name: "Albany", state: "NY", stateName: "New York", population: 99024 },
  { name: "New Rochelle", state: "NY", stateName: "New York", population: 799557 },
  { name: "Mount Vernon", state: "NY", stateName: "New York", population: 73056 },
  { name: "Schenectady", state: "NY", stateName: "New York", population: 67047 },
  { name: "Utica", state: "NY", stateName: "New York", population: 65101 },
  { name: "White Plains", state: "NY", stateName: "New York", population: 59483 },
  { name: "Troy", state: "NY", stateName: "New York", population: 50129 },
  { name: "Niagara Falls", state: "NY", stateName: "New York", population: 47940 },
  { name: "Binghamton", state: "NY", stateName: "New York", population: 47001 },
  { name: "Freeport", state: "NY", stateName: "New York", population: 43415 },
  { name: "Valley Stream", state: "NY", stateName: "New York", population: 37511 },
  { name: "Long Beach", state: "NY", stateName: "New York", population: 33575 },
  { name: "Rome", state: "NY", stateName: "New York", population: 32225 },
  { name: "Ithaca", state: "NY", stateName: "New York", population: 32108 },
  { name: "Poughkeepsie", state: "NY", stateName: "New York", population: 30415 },
  { name: "Levittown", state: "NY", stateName: "New York", population: 51881 },
  { name: "Newburgh", state: "NY", stateName: "New York", population: 28666 },
  { name: "Auburn", state: "NY", stateName: "New York", population: 26209 },
  { name: "Watertown", state: "NY", stateName: "New York", population: 25206 },
  { name: "Jamestown", state: "NY", stateName: "New York", population: 28465 },
  { name: "Elmira", state: "NY", stateName: "New York", population: 26659 },
  { name: "Middletown", state: "NY", stateName: "New York", population: 28086 },
  { name: "Kingston", state: "NY", stateName: "New York", population: 23157 },
  { name: "Mineola", state: "NY", stateName: "New York", population: 18799 },
  { name: "Hempstead", state: "NY", stateName: "New York", population: 75974 },
  { name: "Brookhaven", state: "NY", stateName: "New York", population: 486138 },
  { name: "Islip", state: "NY", stateName: "New York", population: 339819 },
  { name: "Oyster Bay", state: "NY", stateName: "New York", population: 293214 },
  { name: "Huntington", state: "NY", stateName: "New York", population: 203264 },
  { name: "Babylon", state: "NY", stateName: "New York", population: 211792 },
  { name: "Smithtown", state: "NY", stateName: "New York", population: 117801 },
  { name: "Riverhead", state: "NY", stateName: "New York", population: 33506 },
  { name: "Southampton", state: "NY", stateName: "New York", population: 58408 },
  { name: "East Hampton", state: "NY", stateName: "New York", population: 21357 },
  { name: "Shelter Island", state: "NY", stateName: "New York", population: 2433 },
  { name: "Southold", state: "NY", stateName: "New York", population: 23084 },
  { name: "Brookhaven", state: "NY", stateName: "New York", population: 486138 },
  { name: "Islip", state: "NY", stateName: "New York", population: 339819 },
  { name: "Oyster Bay", state: "NY", stateName: "New York", population: 293214 },
  { name: "Huntington", state: "NY", stateName: "New York", population: 203264 },
  { name: "Babylon", state: "NY", stateName: "New York", population: 211792 },
  { name: "Smithtown", state: "NY", stateName: "New York", population: 117801 },
  { name: "Riverhead", state: "NY", stateName: "New York", population: 33506 },
  { name: "Southampton", state: "NY", stateName: "New York", population: 58408 },
  { name: "East Hampton", state: "NY", stateName: "New York", population: 21357 },
  { name: "Shelter Island", state: "NY", stateName: "New York", population: 2433 },
  { name: "Southold", state: "NY", stateName: "New York", population: 23084 },
  { name: "Glen Cove", state: "NY", stateName: "New York", population: 27172 },
  { name: "Long Beach", state: "NY", stateName: "New York", population: 33575 },
  { name: "New Rochelle", state: "NY", stateName: "New York", population: 799557 },
  { name: "Mount Vernon", state: "NY", stateName: "New York", population: 73056 },
  { name: "White Plains", state: "NY", stateName: "New York", population: 59483 },
  { name: "Yonkers", state: "NY", stateName: "New York", population: 211569 },
  { name: "Peekskill", state: "NY", stateName: "New York", population: 24113 },
  { name: "Rye", state: "NY", stateName: "New York", population: 15967 },
  { name: "Port Chester", state: "NY", stateName: "New York", population: 30967 },
  { name: "Harrison", state: "NY", stateName: "New York", population: 28356 },
  { name: "Mamaroneck", state: "NY", stateName: "New York", population: 19251 },
  { name: "Larchmont", state: "NY", stateName: "New York", population: 5899 },
  { name: "Pelham", state: "NY", stateName: "New York", population: 6986 },
  { name: "Bronxville", state: "NY", stateName: "New York", population: 6455 },
  { name: "Tuckahoe", state: "NY", stateName: "New York", population: 6546 },
  { name: "Eastchester", state: "NY", stateName: "New York", population: 34077 },
  { name: "Scarsdale", state: "NY", stateName: "New York", population: 17766 },
  { name: "Edgemont", state: "NY", stateName: "New York", population: 7657 },
  { name: "Greenburgh", state: "NY", stateName: "New York", population: 95135 },
  { name: "Mount Pleasant", state: "NY", stateName: "New York", population: 44169 },
  { name: "New Castle", state: "NY", stateName: "New York", population: 18177 },
  { name: "North Castle", state: "NY", stateName: "New York", population: 11941 },
  { name: "Pound Ridge", state: "NY", stateName: "New York", population: 5071 },
  { name: "Somers", state: "NY", stateName: "New York", population: 20434 },
  { name: "Yorktown", state: "NY", stateName: "New York", population: 36869 },
  { name: "Lewisboro", state: "NY", stateName: "New York", population: 12411 },
  { name: "Bedford", state: "NY", stateName: "New York", population: 17325 },
  { name: "Pound Ridge", state: "NY", stateName: "New York", population: 5071 },
  { name: "North Salem", state: "NY", stateName: "New York", population: 5120 },
  { name: "Somers", state: "NY", stateName: "New York", population: 20434 },
  { name: "Yorktown", state: "NY", stateName: "New York", population: 36869 },
  { name: "Cortlandt", state: "NY", stateName: "New York", population: 41192 },
  { name: "Ossining", state: "NY", stateName: "New York", population: 39105 },
  { name: "Briarcliff Manor", state: "NY", stateName: "New York", population: 7964 },
  { name: "Croton-on-Hudson", state: "NY", stateName: "New York", population: 8113 },
  { name: "Buchanan", state: "NY", stateName: "New York", population: 2153 },
  { name: "Peekskill", state: "NY", stateName: "New York", population: 24113 },
  { name: "Verplanck", state: "NY", stateName: "New York", population: 1743 },
  { name: "Montrose", state: "NY", stateName: "New York", population: 2778 },
  { name: "Buchanan", state: "NY", stateName: "New York", population: 2153 },
  { name: "Croton-on-Hudson", state: "NY", stateName: "New York", population: 8113 },
  { name: "Briarcliff Manor", state: "NY", stateName: "New York", population: 7964 },
  { name: "Ossining", state: "NY", stateName: "New York", population: 39105 },
  { name: "Cortlandt", state: "NY", stateName: "New York", population: 41192 },
  { name: "Yorktown", state: "NY", stateName: "New York", population: 36869 },
  { name: "Somers", state: "NY", stateName: "New York", population: 20434 },
  { name: "North Salem", state: "NY", stateName: "New York", population: 5120 },
  { name: "Pound Ridge", state: "NY", stateName: "New York", population: 5071 },
  { name: "Bedford", state: "NY", stateName: "New York", population: 17325 },
  { name: "Lewisboro", state: "NY", stateName: "New York", population: 12411 },
  { name: "Yorktown", state: "NY", stateName: "New York", population: 36869 },
  { name: "Somers", state: "NY", stateName: "New York", population: 20434 },
  { name: "North Salem", state: "NY", stateName: "New York", population: 5120 },
  { name: "Pound Ridge", state: "NY", stateName: "New York", population: 5071 },
  { name: "Bedford", state: "NY", stateName: "New York", population: 17325 },
  { name: "Lewisboro", state: "NY", stateName: "New York", population: 12411 },
  { name: "Yorktown", state: "NY", stateName: "New York", population: 36869 },
  { name: "Somers", state: "NY", stateName: "New York", population: 20434 },
  { name: "North Salem", state: "NY", stateName: "New York", population: 5120 },
  { name: "Pound Ridge", state: "NY", stateName: "New York", population: 5071 },
  { name: "Bedford", state: "NY", stateName: "New York", population: 17325 },
  { name: "Lewisboro", state: "NY", stateName: "New York", population: 12411 },

  // North Carolina
  { name: "Charlotte", state: "NC", stateName: "North Carolina", population: 885708 },
  { name: "Raleigh", state: "NC", stateName: "North Carolina", population: 474069 },
  { name: "Greensboro", state: "NC", stateName: "North Carolina", population: 298263 },
  { name: "Durham", state: "NC", stateName: "North Carolina", population: 278993 },
  { name: "Winston-Salem", state: "NC", stateName: "North Carolina", population: 247945 },
  { name: "Fayetteville", state: "NC", stateName: "North Carolina", population: 208501 },
  { name: "Cary", state: "NC", stateName: "North Carolina", population: 174721 },
  { name: "Wilmington", state: "NC", stateName: "North Carolina", population: 123784 },
  { name: "High Point", state: "NC", stateName: "North Carolina", population: 114059 },
  { name: "Concord", state: "NC", stateName: "North Carolina", population: 105240 },
  { name: "Asheville", state: "NC", stateName: "North Carolina", population: 94298 },
  { name: "Gastonia", state: "NC", stateName: "North Carolina", population: 80709 },
  { name: "Jacksonville", state: "NC", stateName: "North Carolina", population: 72923 },
  { name: "Chapel Hill", state: "NC", stateName: "North Carolina", population: 61960 },
  { name: "Rocky Mount", state: "NC", stateName: "North Carolina", population: 54441 },
  { name: "Burlington", state: "NC", stateName: "North Carolina", population: 57004 },
  { name: "Wilson", state: "NC", stateName: "North Carolina", population: 49767 },
  { name: "Huntersville", state: "NC", stateName: "North Carolina", population: 57239 },
  { name: "Kannapolis", state: "NC", stateName: "North Carolina", population: 53114 },
  { name: "Apex", state: "NC", stateName: "North Carolina", population: 58178 },
  { name: "Hickory", state: "NC", stateName: "North Carolina", population: 43087 },
  { name: "Goldsboro", state: "NC", stateName: "North Carolina", population: 34597 },
  { name: "Greenville", state: "NC", stateName: "North Carolina", population: 87263 },
  { name: "Salisbury", state: "NC", stateName: "North Carolina", population: 34801 },
  { name: "Sanford", state: "NC", stateName: "North Carolina", population: 30096 },
  { name: "Monroe", state: "NC", stateName: "North Carolina", population: 34462 },
  { name: "Mooresville", state: "NC", stateName: "North Carolina", population: 50817 },
  { name: "New Bern", state: "NC", stateName: "North Carolina", population: 30242 },
  { name: "Statesville", state: "NC", stateName: "North Carolina", population: 28419 },
  { name: "Thomasville", state: "NC", stateName: "North Carolina", population: 27227 },
  { name: "Cornelius", state: "NC", stateName: "North Carolina", population: 31105 },
  { name: "Matthews", state: "NC", stateName: "North Carolina", population: 32882 },
  { name: "Mint Hill", state: "NC", stateName: "North Carolina", population: 27112 },
  { name: "Harrisburg", state: "NC", stateName: "North Carolina", population: 18097 },
  { name: "Indian Trail", state: "NC", stateName: "North Carolina", population: 39677 },
  { name: "Waxhaw", state: "NC", stateName: "North Carolina", population: 20097 },
  { name: "Weddington", state: "NC", stateName: "North Carolina", population: 11231 },
  { name: "Stallings", state: "NC", stateName: "North Carolina", population: 15806 },
  { name: "Pineville", state: "NC", stateName: "North Carolina", population: 8911 },
  { name: "Davidson", state: "NC", stateName: "North Carolina", population: 13582 },
  { name: "Belmont", state: "NC", stateName: "North Carolina", population: 15233 },
  { name: "Mount Holly", state: "NC", stateName: "North Carolina", population: 15986 },
  { name: "Lowell", state: "NC", stateName: "North Carolina", population: 3646 },
  { name: "Dallas", state: "NC", stateName: "North Carolina", population: 5183 },
  { name: "Cherryville", state: "NC", stateName: "North Carolina", population: 5904 },
  { name: "Cramerton", state: "NC", stateName: "North Carolina", population: 4325 },
  { name: "Ranlo", state: "NC", stateName: "North Carolina", population: 3566 },
  { name: "South Gastonia", state: "NC", stateName: "North Carolina", population: 5727 },
  { name: "Bessemer City", state: "NC", stateName: "North Carolina", population: 5436 },
  { name: "Stanley", state: "NC", stateName: "North Carolina", population: 3756 },
  { name: "McAdenville", state: "NC", stateName: "North Carolina", population: 651 },
  { name: "High Shoals", state: "NC", stateName: "North Carolina", population: 693 },
  { name: "Spencer Mountain", state: "NC", stateName: "North Carolina", population: 37 },
  { name: "Iron Station", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Lincolnton", state: "NC", stateName: "North Carolina", population: 11319 },
  { name: "Vale", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Crouse", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Denver", state: "NC", stateName: "North Carolina", population: 2747 },
  { name: "Westport", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Long Shoals", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Pumpkin Center", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Boger City", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Cat Square", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Howards Creek", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "North Brook", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Westport", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Long Shoals", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Pumpkin Center", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Boger City", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Cat Square", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "Howards Creek", state: "NC", stateName: "North Carolina", population: 0 },
  { name: "North Brook", state: "NC", stateName: "North Carolina", population: 0 }
];

module.exports = finalCities;
