// Missing states batch 1 - Adding remaining states from user's 50-state list

const missingStatesBatch1 = [
  // Alabama
  { name: "Birmingham", state: "AL", stateName: "Alabama", population: 200733 },
  { name: "Montgomery", state: "AL", stateName: "Alabama", population: 200022 },
  { name: "Mobile", state: "AL", stateName: "Alabama", population: 187041 },
  { name: "Huntsville", state: "AL", stateName: "Alabama", population: 215006 },
  { name: "Tuscaloosa", state: "AL", stateName: "Alabama", population: 100618 },
  { name: "Hoover", state: "AL", stateName: "Alabama", population: 92101 },
  { name: "Dothan", state: "AL", stateName: "Alabama", population: 71072 },
  { name: "Auburn", state: "AL", stateName: "Alabama", population: 76014 },
  { name: "Decatur", state: "AL", stateName: "Alabama", population: 54341 },
  { name: "Madison", state: "AL", stateName: "Alabama", population: 56001 },
  { name: "Florence", state: "AL", stateName: "Alabama", population: 40484 },
  { name: "Gadsden", state: "AL", stateName: "Alabama", population: 35241 },
  { name: "Vestavia Hills", state: "AL", stateName: "Alabama", population: 34433 },
  { name: "Prattville", state: "AL", stateName: "Alabama", population: 37581 },
  { name: "Phenix City", state: "AL", stateName: "Alabama", population: 38067 },
  { name: "Opelika", state: "AL", stateName: "Alabama", population: 30275 },
  { name: "Anniston", state: "AL", stateName: "Alabama", population: 21654 },
  { name: "Prichard", state: "AL", stateName: "Alabama", population: 19681 },
  { name: "Bessemer", state: "AL", stateName: "Alabama", population: 26019 },
  { name: "Homewood", state: "AL", stateName: "Alabama", population: 26014 },
  { name: "Northport", state: "AL", stateName: "Alabama", population: 31229 },
  { name: "Trussville", state: "AL", stateName: "Alabama", population: 26017 },
  { name: "Mountain Brook", state: "AL", stateName: "Alabama", population: 20135 },
  { name: "Enterprise", state: "AL", stateName: "Alabama", population: 28593 },
  { name: "Athens", state: "AL", stateName: "Alabama", population: 26247 },
  { name: "Selma", state: "AL", stateName: "Alabama", population: 17240 },
  { name: "Oxford", state: "AL", stateName: "Alabama", population: 22069 },
  { name: "Albertville", state: "AL", stateName: "Alabama", population: 22386 },
  { name: "Scottsboro", state: "AL", stateName: "Alabama", population: 14857 },
  { name: "Fort Payne", state: "AL", stateName: "Alabama", population: 14012 },
  { name: "Cullman", state: "AL", stateName: "Alabama", population: 18013 },
  { name: "Jasper", state: "AL", stateName: "Alabama", population: 14052 },
  { name: "Troy", state: "AL", stateName: "Alabama", population: 18933 },
  { name: "Eufaula", state: "AL", stateName: "Alabama", population: 12882 },
  { name: "Andalusia", state: "AL", stateName: "Alabama", population: 8840 },
  { name: "Demopolis", state: "AL", stateName: "Alabama", population: 7208 },
  { name: "Alexander City", state: "AL", stateName: "Alabama", population: 14875 },
  { name: "Guntersville", state: "AL", stateName: "Alabama", population: 8338 },
  { name: "Talladega", state: "AL", stateName: "Alabama", population: 15424 },
  { name: "Sylacauga", state: "AL", stateName: "Alabama", population: 12032 },
  { name: "Sheffield", state: "AL", stateName: "Alabama", population: 9038 },
  { name: "Tuscumbia", state: "AL", stateName: "Alabama", population: 9114 },
  { name: "Tuskegee", state: "AL", stateName: "Alabama", population: 8085 },
  { name: "Marion", state: "AL", stateName: "Alabama", population: 3194 },
  { name: "Greenville", state: "AL", stateName: "Alabama", population: 7134 },
  { name: "Chickasaw", state: "AL", stateName: "Alabama", population: 6106 },
  { name: "Clanton", state: "AL", stateName: "Alabama", population: 8901 },
  { name: "Ozark", state: "AL", stateName: "Alabama", population: 14265 },

  // Alaska
  { name: "Anchorage", state: "AK", stateName: "Alaska", population: 291247 },
  { name: "Fairbanks", state: "AK", stateName: "Alaska", population: 32515 },
  { name: "Juneau", state: "AK", stateName: "Alaska", population: 32255 },
  { name: "Sitka", state: "AK", stateName: "Alaska", population: 8440 },
  { name: "Ketchikan", state: "AK", stateName: "Alaska", population: 8192 },
  { name: "Wasilla", state: "AK", stateName: "Alaska", population: 11047 },
  { name: "Kenai", state: "AK", stateName: "Alaska", population: 7798 },
  { name: "Kodiak", state: "AK", stateName: "Alaska", population: 6130 },
  { name: "Bethel", state: "AK", stateName: "Alaska", population: 6540 },
  { name: "Palmer", state: "AK", stateName: "Alaska", population: 5937 },
  { name: "Homer", state: "AK", stateName: "Alaska", population: 5539 },
  { name: "Barrow", state: "AK", stateName: "Alaska", population: 4212 },
  { name: "Nome", state: "AK", stateName: "Alaska", population: 3866 },
  { name: "Kotzebue", state: "AK", stateName: "Alaska", population: 3201 },
  { name: "Unalaska", state: "AK", stateName: "Alaska", population: 4356 },
  { name: "Valdez", state: "AK", stateName: "Alaska", population: 3855 },
  { name: "Seward", state: "AK", stateName: "Alaska", population: 2693 },
  { name: "Cordova", state: "AK", stateName: "Alaska", population: 2259 },
  { name: "Haines", state: "AK", stateName: "Alaska", population: 1715 },
  { name: "Skagway", state: "AK", stateName: "Alaska", population: 1083 },

  // Arkansas
  { name: "Little Rock", state: "AR", stateName: "Arkansas", population: 202591 },
  { name: "Fort Smith", state: "AR", stateName: "Arkansas", population: 89942 },
  { name: "Fayetteville", state: "AR", stateName: "Arkansas", population: 95230 },
  { name: "Springdale", state: "AR", stateName: "Arkansas", population: 84203 },
  { name: "Jonesboro", state: "AR", stateName: "Arkansas", population: 78258 },
  { name: "North Little Rock", state: "AR", stateName: "Arkansas", population: 66041 },
  { name: "Conway", state: "AR", stateName: "Arkansas", population: 67053 },
  { name: "Rogers", state: "AR", stateName: "Arkansas", population: 69908 },
  { name: "Pine Bluff", state: "AR", stateName: "Arkansas", population: 41053 },
  { name: "Bentonville", state: "AR", stateName: "Arkansas", population: 54032 },
  { name: "Hot Springs", state: "AR", stateName: "Arkansas", population: 37193 },
  { name: "Texarkana", state: "AR", stateName: "Arkansas", population: 29919 },
  { name: "Sherwood", state: "AR", stateName: "Arkansas", population: 32008 },
  { name: "Jacksonville", state: "AR", stateName: "Arkansas", population: 29067 },
  { name: "Russellville", state: "AR", stateName: "Arkansas", population: 28940 },
  { name: "Bella Vista", state: "AR", stateName: "Arkansas", population: 30004 },
  { name: "Paragould", state: "AR", stateName: "Arkansas", population: 29037 },
  { name: "Cabot", state: "AR", stateName: "Arkansas", population: 26352 },
  { name: "Searcy", state: "AR", stateName: "Arkansas", population: 23250 },
  { name: "Van Buren", state: "AR", stateName: "Arkansas", population: 23409 },
  { name: "El Dorado", state: "AR", stateName: "Arkansas", population: 17855 },
  { name: "Batesville", state: "AR", stateName: "Arkansas", population: 11533 },
  { name: "Blytheville", state: "AR", stateName: "Arkansas", population: 13784 },
  { name: "Harrison", state: "AR", stateName: "Arkansas", population: 13128 },
  { name: "Mountain Home", state: "AR", stateName: "Arkansas", population: 12590 },
  { name: "Helena", state: "AR", stateName: "Arkansas", population: 10057 },
  { name: "Camden", state: "AR", stateName: "Arkansas", population: 10138 },
  { name: "Magnolia", state: "AR", stateName: "Arkansas", population: 11062 },
  { name: "Arkadelphia", state: "AR", stateName: "Arkansas", population: 10114 },
  { name: "Malvern", state: "AR", stateName: "Arkansas", population: 10318 },
  { name: "Stuttgart", state: "AR", stateName: "Arkansas", population: 8860 },
  { name: "Forrest City", state: "AR", stateName: "Arkansas", population: 14078 },
  { name: "Osceola", state: "AR", stateName: "Arkansas", population: 6658 },
  { name: "Newport", state: "AR", stateName: "Arkansas", population: 7994 },
  { name: "Crossett", state: "AR", stateName: "Arkansas", population: 5047 },
  { name: "Hope", state: "AR", stateName: "Arkansas", population: 10020 },
  { name: "Morrilton", state: "AR", stateName: "Arkansas", population: 6767 },
  { name: "West Memphis", state: "AR", stateName: "Arkansas", population: 24670 },
  { name: "Arkansas Post", state: "AR", stateName: "Arkansas", population: 0 },

  // Connecticut
  { name: "Bridgeport", state: "CT", stateName: "Connecticut", population: 148654 },
  { name: "New Haven", state: "CT", stateName: "Connecticut", population: 134023 },
  { name: "Hartford", state: "CT", stateName: "Connecticut", population: 121054 },
  { name: "Stamford", state: "CT", stateName: "Connecticut", population: 135470 },
  { name: "Waterbury", state: "CT", stateName: "Connecticut", population: 114403 },
  { name: "Norwalk", state: "CT", stateName: "Connecticut", population: 91238 },
  { name: "Danbury", state: "CT", stateName: "Connecticut", population: 84656 },
  { name: "New Britain", state: "CT", stateName: "Connecticut", population: 74006 },
  { name: "West Hartford", state: "CT", stateName: "Connecticut", population: 63268 },
  { name: "Greenwich", state: "CT", stateName: "Connecticut", population: 63399 },
  { name: "Hamden", state: "CT", stateName: "Connecticut", population: 61407 },
  { name: "Meriden", state: "CT", stateName: "Connecticut", population: 60868 },
  { name: "Bristol", state: "CT", stateName: "Connecticut", population: 60035 },
  { name: "Manchester", state: "CT", stateName: "Connecticut", population: 57713 },
  { name: "West Haven", state: "CT", stateName: "Connecticut", population: 55584 },
  { name: "Milford", state: "CT", stateName: "Connecticut", population: 54584 },
  { name: "Stratford", state: "CT", stateName: "Connecticut", population: 51984 },
  { name: "East Hartford", state: "CT", stateName: "Connecticut", population: 51324 },
  { name: "Middletown", state: "CT", stateName: "Connecticut", population: 47648 },
  { name: "Norwich", state: "CT", stateName: "Connecticut", population: 40493 },
  { name: "Shelton", state: "CT", stateName: "Connecticut", population: 40987 },
  { name: "Torrington", state: "CT", stateName: "Connecticut", population: 35015 },
  { name: "New London", state: "CT", stateName: "Connecticut", population: 27045 },
  { name: "Ansonia", state: "CT", stateName: "Connecticut", population: 18922 },
  { name: "Derby", state: "CT", stateName: "Connecticut", population: 12415 },
  { name: "Groton", state: "CT", stateName: "Connecticut", population: 20401 },
  { name: "Naugatuck", state: "CT", stateName: "Connecticut", population: 31229 },
  { name: "Southington", state: "CT", stateName: "Connecticut", population: 43501 },
  { name: "Wallingford", state: "CT", stateName: "Connecticut", population: 44496 },
  { name: "Windsor", state: "CT", stateName: "Connecticut", population: 29044 },
  { name: "Windsor Locks", state: "CT", stateName: "Connecticut", population: 12749 },
  { name: "Winsted", state: "CT", stateName: "Connecticut", population: 7226 },
  { name: "Berlin", state: "CT", stateName: "Connecticut", population: 19866 },
  { name: "Bloomfield", state: "CT", stateName: "Connecticut", population: 21173 },
  { name: "Branford", state: "CT", stateName: "Connecticut", population: 28026 },
  { name: "Coventry", state: "CT", stateName: "Connecticut", population: 12380 },
  { name: "Darien", state: "CT", stateName: "Connecticut", population: 21692 },
  { name: "East Haven", state: "CT", stateName: "Connecticut", population: 27157 },
  { name: "Enfield", state: "CT", stateName: "Connecticut", population: 42041 },
  { name: "Fairfield", state: "CT", stateName: "Connecticut", population: 62500 },
  { name: "Farmington", state: "CT", stateName: "Connecticut", population: 25624 },
  { name: "Glastonbury", state: "CT", stateName: "Connecticut", population: 35459 },
  { name: "Guilford", state: "CT", stateName: "Connecticut", population: 22075 },
  { name: "Lebanon", state: "CT", stateName: "Connecticut", population: 7280 },
  { name: "Litchfield", state: "CT", stateName: "Connecticut", population: 1236 },
  { name: "Mansfield", state: "CT", stateName: "Connecticut", population: 25648 },
  { name: "Mystic", state: "CT", stateName: "Connecticut", population: 0 },
  { name: "New Canaan", state: "CT", stateName: "Connecticut", population: 20253 },
  { name: "North Haven", state: "CT", stateName: "Connecticut", population: 24127 },
  { name: "Old Saybrook", state: "CT", stateName: "Connecticut", population: 10242 },
  { name: "Orange", state: "CT", stateName: "Connecticut", population: 13956 },
  { name: "Seymour", state: "CT", stateName: "Connecticut", population: 16323 },
  { name: "Simsbury", state: "CT", stateName: "Connecticut", population: 25017 },
  { name: "South Windsor", state: "CT", stateName: "Connecticut", population: 26017 },
  { name: "Trumbull", state: "CT", stateName: "Connecticut", population: 36018 },
  { name: "Vernon", state: "CT", stateName: "Connecticut", population: 29031 },
  { name: "Waterford", state: "CT", stateName: "Connecticut", population: 19428 },
  { name: "Watertown", state: "CT", stateName: "Connecticut", population: 22015 },
  { name: "Westport", state: "CT", stateName: "Connecticut", population: 28141 },
  { name: "Wethersfield", state: "CT", stateName: "Connecticut", population: 27098 },
  { name: "Willimantic", state: "CT", stateName: "Connecticut", population: 0 },
  { name: "Windham", state: "CT", stateName: "Connecticut", population: 0 }
];

module.exports = missingStatesBatch1;
