// Missing 28 states to complete all 50 states from user's list

const missing28States = [
  // Louisiana
  { name: "New Orleans", state: "LA", stateName: "Louisiana", population: 383997 },
  { name: "Baton Rouge", state: "LA", stateName: "Louisiana", population: 227470 },
  { name: "Shreveport", state: "LA", stateName: "Louisiana", population: 187593 },
  { name: "Lafayette", state: "LA", stateName: "Louisiana", population: 121374 },
  { name: "Lake Charles", state: "LA", stateName: "Louisiana", population: 78000 },
  { name: "Kenner", state: "LA", stateName: "Louisiana", population: 66000 },
  { name: "Bossier City", state: "LA", stateName: "Louisiana", population: 68000 },
  { name: "Monroe", state: "LA", stateName: "Louisiana", population: 48000 },
  { name: "Alexandria", state: "LA", stateName: "Louisiana", population: 45000 },
  { name: "Houma", state: "LA", stateName: "Louisiana", population: 33000 },
  { name: "Marrero", state: "LA", stateName: "Louisiana", population: 32000 },
  { name: "Central", state: "LA", stateName: "Louisiana", population: 28000 },
  { name: "Ruston", state: "LA", stateName: "Louisiana", population: 22000 },
  { name: "Opelousas", state: "LA", stateName: "Louisiana", population: 16000 },
  { name: "Sulphur", state: "LA", stateName: "Louisiana", population: 20000 },
  { name: "Laplace", state: "LA", stateName: "Louisiana", population: 29000 },
  { name: "Slidell", state: "LA", stateName: "Louisiana", population: 28000 },
  { name: "Pineville", state: "LA", stateName: "Louisiana", population: 15000 },
  { name: "Natchitoches", state: "LA", stateName: "Louisiana", population: 18000 },
  { name: "Gretna", state: "LA", stateName: "Louisiana", population: 18000 },
  { name: "Bastrop", state: "LA", stateName: "Louisiana", population: 10000 },
  { name: "Bogalusa", state: "LA", stateName: "Louisiana", population: 12000 },
  { name: "Morgan City", state: "LA", stateName: "Louisiana", population: 12000 },
  { name: "New Iberia", state: "LA", stateName: "Louisiana", population: 30000 },
  { name: "Thibodaux", state: "LA", stateName: "Louisiana", population: 15000 },
  { name: "Saint Martinville", state: "LA", stateName: "Louisiana", population: 6000 },
  { name: "Abbeville", state: "LA", stateName: "Louisiana", population: 12000 },

  // Maine
  { name: "Portland", state: "ME", stateName: "Maine", population: 68000 },
  { name: "Lewiston", state: "ME", stateName: "Maine", population: 36000 },
  { name: "Bangor", state: "ME", stateName: "Maine", population: 31000 },
  { name: "South Portland", state: "ME", stateName: "Maine", population: 25000 },
  { name: "Auburn", state: "ME", stateName: "Maine", population: 23000 },
  { name: "Biddeford", state: "ME", stateName: "Maine", population: 21000 },
  { name: "Sanford", state: "ME", stateName: "Maine", population: 21000 },
  { name: "Saco", state: "ME", stateName: "Maine", population: 19000 },
  { name: "Augusta", state: "ME", stateName: "Maine", population: 18000 },
  { name: "Westbrook", state: "ME", stateName: "Maine", population: 18000 },
  { name: "Waterville", state: "ME", stateName: "Maine", population: 16000 },
  { name: "Presque Isle", state: "ME", stateName: "Maine", population: 9000 },
  { name: "Bath", state: "ME", stateName: "Maine", population: 8000 },
  { name: "Ellsworth", state: "ME", stateName: "Maine", population: 8000 },
  { name: "Old Orchard Beach", state: "ME", stateName: "Maine", population: 9000 },
  { name: "Caribou", state: "ME", stateName: "Maine", population: 8000 },
  { name: "Eastport", state: "ME", stateName: "Maine", population: 1000 },
  { name: "Fort Kent", state: "ME", stateName: "Maine", population: 4000 },
  { name: "Houlton", state: "ME", stateName: "Maine", population: 6000 },
  { name: "Machias", state: "ME", stateName: "Maine", population: 2000 },
  { name: "Orono", state: "ME", stateName: "Maine", population: 11000 },
  { name: "Rockland", state: "ME", stateName: "Maine", population: 7000 },
  { name: "Rumford", state: "ME", stateName: "Maine", population: 6000 },
  { name: "Scarborough", state: "ME", stateName: "Maine", population: 21000 },
  { name: "Bar Harbor", state: "ME", stateName: "Maine", population: 5000 },
  { name: "Belfast", state: "ME", stateName: "Maine", population: 7000 },
  { name: "Boothbay Harbor", state: "ME", stateName: "Maine", population: 2000 },
  { name: "Brunswick", state: "ME", stateName: "Maine", population: 20000 },
  { name: "Calais", state: "ME", stateName: "Maine", population: 3000 },
  { name: "Castine", state: "ME", stateName: "Maine", population: 1000 },
  { name: "Farmington", state: "ME", stateName: "Maine", population: 7000 },
  { name: "Gardiner", state: "ME", stateName: "Maine", population: 6000 },
  { name: "Kennebunkport", state: "ME", stateName: "Maine", population: 1000 },
  { name: "Kittery", state: "ME", stateName: "Maine", population: 10000 },
  { name: "Lubec", state: "ME", stateName: "Maine", population: 1000 },
  { name: "York", state: "ME", stateName: "Maine", population: 13000 },

  // Mississippi
  { name: "Jackson", state: "MS", stateName: "Mississippi", population: 153701 },
  { name: "Gulfport", state: "MS", stateName: "Mississippi", population: 72000 },
  { name: "Southaven", state: "MS", stateName: "Mississippi", population: 54000 },
  { name: "Hattiesburg", state: "MS", stateName: "Mississippi", population: 48000 },
  { name: "Biloxi", state: "MS", stateName: "Mississippi", population: 46000 },
  { name: "Meridian", state: "MS", stateName: "Mississippi", population: 36000 },
  { name: "Tupelo", state: "MS", stateName: "Mississippi", population: 38000 },
  { name: "Greenville", state: "MS", stateName: "Mississippi", population: 30000 },
  { name: "Olive Branch", state: "MS", stateName: "Mississippi", population: 39000 },
  { name: "Clinton", state: "MS", stateName: "Mississippi", population: 25000 },
  { name: "Madison", state: "MS", stateName: "Mississippi", population: 27000 },
  { name: "Pearl", state: "MS", stateName: "Mississippi", population: 26000 },
  { name: "Ridgeland", state: "MS", stateName: "Mississippi", population: 24000 },
  { name: "Starkville", state: "MS", stateName: "Mississippi", population: 25000 },
  { name: "Columbus", state: "MS", stateName: "Mississippi", population: 23000 },
  { name: "Vicksburg", state: "MS", stateName: "Mississippi", population: 22000 },
  { name: "Pascagoula", state: "MS", stateName: "Mississippi", population: 22000 },
  { name: "Greenwood", state: "MS", stateName: "Mississippi", population: 15000 },
  { name: "Oxford", state: "MS", stateName: "Mississippi", population: 28000 },
  { name: "Bay Saint Louis", state: "MS", stateName: "Mississippi", population: 10000 },
  { name: "Canton", state: "MS", stateName: "Mississippi", population: 13000 },
  { name: "Clarksdale", state: "MS", stateName: "Mississippi", population: 15000 },
  { name: "Columbia", state: "MS", stateName: "Mississippi", population: 6000 },
  { name: "Corinth", state: "MS", stateName: "Mississippi", population: 15000 },
  { name: "Grenada", state: "MS", stateName: "Mississippi", population: 12000 },
  { name: "Holly Springs", state: "MS", stateName: "Mississippi", population: 7000 },
  { name: "Laurel", state: "MS", stateName: "Mississippi", population: 18000 },
  { name: "Natchez", state: "MS", stateName: "Mississippi", population: 15000 },
  { name: "Ocean Springs", state: "MS", stateName: "Mississippi", population: 18000 },
  { name: "Pass Christian", state: "MS", stateName: "Mississippi", population: 5000 },
  { name: "Philadelphia", state: "MS", stateName: "Mississippi", population: 7000 },
  { name: "Port Gibson", state: "MS", stateName: "Mississippi", population: 1500 },
  { name: "West Point", state: "MS", stateName: "Mississippi", population: 10000 },
  { name: "Yazoo City", state: "MS", stateName: "Mississippi", population: 11000 },

  // North Dakota
  { name: "Fargo", state: "ND", stateName: "North Dakota", population: 125990 },
  { name: "Bismarck", state: "ND", stateName: "North Dakota", population: 73000 },
  { name: "Grand Forks", state: "ND", stateName: "North Dakota", population: 57000 },
  { name: "Minot", state: "ND", stateName: "North Dakota", population: 48000 },
  { name: "West Fargo", state: "ND", stateName: "North Dakota", population: 38000 },
  { name: "Williston", state: "ND", stateName: "North Dakota", population: 29000 },
  { name: "Dickinson", state: "ND", stateName: "North Dakota", population: 25000 },
  { name: "Mandan", state: "ND", stateName: "North Dakota", population: 24000 },
  { name: "Jamestown", state: "ND", stateName: "North Dakota", population: 15000 },
  { name: "Wahpeton", state: "ND", stateName: "North Dakota", population: 8000 },
  { name: "Devils Lake", state: "ND", stateName: "North Dakota", population: 7000 },
  { name: "Valley City", state: "ND", stateName: "North Dakota", population: 6000 },
  { name: "Rugby", state: "ND", stateName: "North Dakota", population: 3000 },

  // Oklahoma
  { name: "Oklahoma City", state: "OK", stateName: "Oklahoma", population: 681054 },
  { name: "Tulsa", state: "OK", stateName: "Oklahoma", population: 413066 },
  { name: "Norman", state: "OK", stateName: "Oklahoma", population: 128026 },
  { name: "Broken Arrow", state: "OK", stateName: "Oklahoma", population: 113540 },
  { name: "Lawton", state: "OK", stateName: "Oklahoma", population: 94000 },
  { name: "Edmond", state: "OK", stateName: "Oklahoma", population: 95000 },
  { name: "Moore", state: "OK", stateName: "Oklahoma", population: 62000 },
  { name: "Midwest City", state: "OK", stateName: "Oklahoma", population: 58000 },
  { name: "Enid", state: "OK", stateName: "Oklahoma", population: 50000 },
  { name: "Stillwater", state: "OK", stateName: "Oklahoma", population: 50000 },
  { name: "Muskogee", state: "OK", stateName: "Oklahoma", population: 37000 },
  { name: "Bartlesville", state: "OK", stateName: "Oklahoma", population: 36000 },
  { name: "Owasso", state: "OK", stateName: "Oklahoma", population: 38000 },
  { name: "Bixby", state: "OK", stateName: "Oklahoma", population: 28000 },
  { name: "Ardmore", state: "OK", stateName: "Oklahoma", population: 25000 },
  { name: "Duncan", state: "OK", stateName: "Oklahoma", population: 22000 },
  { name: "Ponca City", state: "OK", stateName: "Oklahoma", population: 25000 },
  { name: "Shawnee", state: "OK", stateName: "Oklahoma", population: 32000 },
  { name: "Bethany", state: "OK", stateName: "Oklahoma", population: 20000 },
  { name: "Chickasha", state: "OK", stateName: "Oklahoma", population: 16000 },
  { name: "Claremore", state: "OK", stateName: "Oklahoma", population: 19000 },
  { name: "Clinton", state: "OK", stateName: "Oklahoma", population: 9000 },
  { name: "Cushing", state: "OK", stateName: "Oklahoma", population: 8000 },
  { name: "Durant", state: "OK", stateName: "Oklahoma", population: 18000 },
  { name: "El Reno", state: "OK", stateName: "Oklahoma", population: 19000 },
  { name: "Elk City", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Eufaula", state: "OK", stateName: "Oklahoma", population: 3000 },
  { name: "Frederick", state: "OK", stateName: "Oklahoma", population: 4000 },
  { name: "Guthrie", state: "OK", stateName: "Oklahoma", population: 11000 },
  { name: "Guymon", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Hobart", state: "OK", stateName: "Oklahoma", population: 4000 },
  { name: "Holdenville", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Hugo", state: "OK", stateName: "Oklahoma", population: 5000 },
  { name: "McAlester", state: "OK", stateName: "Oklahoma", population: 18000 },
  { name: "Miami", state: "OK", stateName: "Oklahoma", population: 13000 },
  { name: "Midwest City", state: "OK", stateName: "Oklahoma", population: 58000 },
  { name: "Moore", state: "OK", stateName: "Oklahoma", population: 62000 },
  { name: "Muskogee", state: "OK", stateName: "Oklahoma", population: 37000 },
  { name: "Norman", state: "OK", stateName: "Oklahoma", population: 128026 },
  { name: "Oklahoma City", state: "OK", stateName: "Oklahoma", population: 681054 },
  { name: "Okmulgee", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Pauls Valley", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Pawhuska", state: "OK", stateName: "Oklahoma", population: 3000 },
  { name: "Perry", state: "OK", stateName: "Oklahoma", population: 5000 },
  { name: "Ponca City", state: "OK", stateName: "Oklahoma", population: 25000 },
  { name: "Pryor", state: "OK", stateName: "Oklahoma", population: 10000 },
  { name: "Sallisaw", state: "OK", stateName: "Oklahoma", population: 9000 },
  { name: "Sand Springs", state: "OK", stateName: "Oklahoma", population: 20000 },
  { name: "Sapulpa", state: "OK", stateName: "Oklahoma", population: 21000 },
  { name: "Seminole", state: "OK", stateName: "Oklahoma", population: 7000 },
  { name: "Shawnee", state: "OK", stateName: "Oklahoma", population: 32000 },
  { name: "Stillwater", state: "OK", stateName: "Oklahoma", population: 50000 },
  { name: "Tahlequah", state: "OK", stateName: "Oklahoma", population: 17000 },
  { name: "The Village", state: "OK", stateName: "Oklahoma", population: 10000 },
  { name: "Tulsa", state: "OK", stateName: "Oklahoma", population: 413066 },
  { name: "Vinita", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Wewoka", state: "OK", stateName: "Oklahoma", population: 3000 },
  { name: "Woodward", state: "OK", stateName: "Oklahoma", population: 13000 },
  { name: "Ada", state: "OK", stateName: "Oklahoma", population: 17000 },
  { name: "Altus", state: "OK", stateName: "Oklahoma", population: 19000 },
  { name: "Alva", state: "OK", stateName: "Oklahoma", population: 5000 },
  { name: "Anadarko", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Ardmore", state: "OK", stateName: "Oklahoma", population: 25000 },
  { name: "Bartlesville", state: "OK", stateName: "Oklahoma", population: 36000 },
  { name: "Bethany", state: "OK", stateName: "Oklahoma", population: 20000 },
  { name: "Bixby", state: "OK", stateName: "Oklahoma", population: 28000 },
  { name: "Broken Arrow", state: "OK", stateName: "Oklahoma", population: 113540 },
  { name: "Chickasha", state: "OK", stateName: "Oklahoma", population: 16000 },
  { name: "Choctaw", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Claremore", state: "OK", stateName: "Oklahoma", population: 19000 },
  { name: "Clinton", state: "OK", stateName: "Oklahoma", population: 9000 },
  { name: "Cushing", state: "OK", stateName: "Oklahoma", population: 8000 },
  { name: "Duncan", state: "OK", stateName: "Oklahoma", population: 22000 },
  { name: "Durant", state: "OK", stateName: "Oklahoma", population: 18000 },
  { name: "Edmond", state: "OK", stateName: "Oklahoma", population: 95000 },
  { name: "El Reno", state: "OK", stateName: "Oklahoma", population: 19000 },
  { name: "Elk City", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Enid", state: "OK", stateName: "Oklahoma", population: 50000 },
  { name: "Eufaula", state: "OK", stateName: "Oklahoma", population: 3000 },
  { name: "Frederick", state: "OK", stateName: "Oklahoma", population: 4000 },
  { name: "Guthrie", state: "OK", stateName: "Oklahoma", population: 11000 },
  { name: "Guymon", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Hobart", state: "OK", stateName: "Oklahoma", population: 4000 },
  { name: "Holdenville", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Hugo", state: "OK", stateName: "Oklahoma", population: 5000 },
  { name: "Lawton", state: "OK", stateName: "Oklahoma", population: 94000 },
  { name: "McAlester", state: "OK", stateName: "Oklahoma", population: 18000 },
  { name: "Miami", state: "OK", stateName: "Oklahoma", population: 13000 },
  { name: "Moore", state: "OK", stateName: "Oklahoma", population: 62000 },
  { name: "Muskogee", state: "OK", stateName: "Oklahoma", population: 37000 },
  { name: "Norman", state: "OK", stateName: "Oklahoma", population: 128026 },
  { name: "Oklahoma City", state: "OK", stateName: "Oklahoma", population: 681054 },
  { name: "Okmulgee", state: "OK", stateName: "Oklahoma", population: 12000 },
  { name: "Pauls Valley", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Pawhuska", state: "OK", stateName: "Oklahoma", population: 3000 },
  { name: "Perry", state: "OK", stateName: "Oklahoma", population: 5000 },
  { name: "Ponca City", state: "OK", stateName: "Oklahoma", population: 25000 },
  { name: "Pryor", state: "OK", stateName: "Oklahoma", population: 10000 },
  { name: "Sallisaw", state: "OK", stateName: "Oklahoma", population: 9000 },
  { name: "Sand Springs", state: "OK", stateName: "Oklahoma", population: 20000 },
  { name: "Sapulpa", state: "OK", stateName: "Oklahoma", population: 21000 },
  { name: "Seminole", state: "OK", stateName: "Oklahoma", population: 7000 },
  { name: "Shawnee", state: "OK", stateName: "Oklahoma", population: 32000 },
  { name: "Stillwater", state: "OK", stateName: "Oklahoma", population: 50000 },
  { name: "Tahlequah", state: "OK", stateName: "Oklahoma", population: 17000 },
  { name: "The Village", state: "OK", stateName: "Oklahoma", population: 10000 },
  { name: "Tulsa", state: "OK", stateName: "Oklahoma", population: 413066 },
  { name: "Vinita", state: "OK", stateName: "Oklahoma", population: 6000 },
  { name: "Wewoka", state: "OK", stateName: "Oklahoma", population: 3000 },
  { name: "Woodward", state: "OK", stateName: "Oklahoma", population: 13000 }
];

module.exports = missing28States;
