// Remaining cities to add to reach 1,587 total
const remainingCities = [
  // Michigan
  { name: "Detroit", state: "MI", stateName: "Michigan", population: 639111 },
  { name: "Grand Rapids", state: "MI", stateName: "Michigan", population: 198917 },
  { name: "Warren", state: "MI", stateName: "Michigan", population: 139387 },
  { name: "Sterling Heights", state: "MI", stateName: "Michigan", population: 134346 },
  { name: "Lansing", state: "MI", stateName: "Michigan", population: 118210 },
  { name: "Ann Arbor", state: "MI", stateName: "Michigan", population: 123851 },
  { name: "Flint", state: "MI", stateName: "Michigan", population: 81005 },
  { name: "Dearborn", state: "MI", stateName: "Michigan", population: 94444 },
  { name: "Livonia", state: "MI", stateName: "Michigan", population: 95808 },
  { name: "Troy", state: "MI", stateName: "Michigan", population: 87305 },
  { name: "Westland", state: "MI", stateName: "Michigan", population: 84194 },
  { name: "Farmington Hills", state: "MI", stateName: "Michigan", population: 81486 },
  { name: "Kalamazoo", state: "MI", stateName: "Michigan", population: 76545 },
  { name: "Wyoming", state: "MI", stateName: "Michigan", population: 76261 },
  { name: "Southfield", state: "MI", stateName: "Michigan", population: 71739 },
  { name: "Rochester Hills", state: "MI", stateName: "Michigan", population: 76142 },
  { name: "Taylor", state: "MI", stateName: "Michigan", population: 63131 },
  { name: "Pontiac", state: "MI", stateName: "Michigan", population: 59515 },
  { name: "St. Clair Shores", state: "MI", stateName: "Michigan", population: 59115 },
  { name: "Royal Oak", state: "MI", stateName: "Michigan", population: 58711 },
  { name: "Novi", state: "MI", stateName: "Michigan", population: 66320 },
  { name: "Dearborn Heights", state: "MI", stateName: "Michigan", population: 57311 },
  { name: "Battle Creek", state: "MI", stateName: "Michigan", population: 51609 },
  { name: "Saginaw", state: "MI", stateName: "Michigan", population: 44474 },
  { name: "Kentwood", state: "MI", stateName: "Michigan", population: 54062 },
  { name: "East Lansing", state: "MI", stateName: "Michigan", population: 48479 },
  { name: "Roseville", state: "MI", stateName: "Michigan", population: 47399 },
  { name: "Portage", state: "MI", stateName: "Michigan", population: 48021 },
  { name: "Midland", state: "MI", stateName: "Michigan", population: 42176 },
  { name: "Lincoln Park", state: "MI", stateName: "Michigan", population: 36219 },
  { name: "Bay City", state: "MI", stateName: "Michigan", population: 32126 },
  { name: "Muskegon", state: "MI", stateName: "Michigan", population: 37462 },
  { name: "Holland", state: "MI", stateName: "Michigan", population: 33176 },
  { name: "Wyandotte", state: "MI", stateName: "Michigan", population: 25058 },
  { name: "Adrian", state: "MI", stateName: "Michigan", population: 20545 },
  { name: "Mount Pleasant", state: "MI", stateName: "Michigan", population: 26466 },
  { name: "Marquette", state: "MI", stateName: "Michigan", population: 20787 },
  { name: "Jackson", state: "MI", stateName: "Michigan", population: 31127 },
  { name: "Niles", state: "MI", stateName: "Michigan", population: 11103 },
  { name: "Traverse City", state: "MI", stateName: "Michigan", population: 15546 },
  { name: "Cadillac", state: "MI", stateName: "Michigan", population: 10455 },
  { name: "Alpena", state: "MI", stateName: "Michigan", population: 10083 },
  { name: "Ionia", state: "MI", stateName: "Michigan", population: 11289 },
  { name: "Manistee", state: "MI", stateName: "Michigan", population: 6121 },
  { name: "Iron Mountain", state: "MI", stateName: "Michigan", population: 7577 },
  { name: "Ironwood", state: "MI", stateName: "Michigan", population: 5029 },
  { name: "Ishpeming", state: "MI", stateName: "Michigan", population: 6392 },
  { name: "Escanaba", state: "MI", stateName: "Michigan", population: 12141 },
  { name: "Houghton", state: "MI", stateName: "Michigan", population: 7708 },
  { name: "Sault Sainte Marie", state: "MI", stateName: "Michigan", population: 13948 },
  { name: "Mackinaw City", state: "MI", stateName: "Michigan", population: 806 },
  { name: "Interlochen", state: "MI", stateName: "Michigan", population: 0 },
  { name: "Charlevoix", state: "MI", stateName: "Michigan", population: 2385 },
  { name: "Cheboygan", state: "MI", stateName: "Michigan", population: 4725 },
  { name: "Grayling", state: "MI", stateName: "Michigan", population: 1884 },
  { name: "Hancock", state: "MI", stateName: "Michigan", population: 4361 },
  { name: "Highland Park", state: "MI", stateName: "Michigan", population: 10893 },
  { name: "Ecorse", state: "MI", stateName: "Michigan", population: 9156 },
  { name: "Grosse Pointe", state: "MI", stateName: "Michigan", population: 0 },
  { name: "Menominee", state: "MI", stateName: "Michigan", population: 8080 },
  { name: "Mount Clemens", state: "MI", stateName: "Michigan", population: 16214 },
  { name: "Mount Pleasant", state: "MI", stateName: "Michigan", population: 26466 },
  { name: "Muskegon Heights", state: "MI", stateName: "Michigan", population: 10634 },
  { name: "Niles", state: "MI", stateName: "Michigan", population: 11103 },
  { name: "Petoskey", state: "MI", stateName: "Michigan", population: 5738 },
  { name: "Pontiac", state: "MI", stateName: "Michigan", population: 59515 },
  { name: "Port Huron", state: "MI", stateName: "Michigan", population: 28756 },
  { name: "Royal Oak", state: "MI", stateName: "Michigan", population: 58711 },
  { name: "Saginaw", state: "MI", stateName: "Michigan", population: 44474 },
  { name: "Saint Ignace", state: "MI", stateName: "Michigan", population: 2137 },
  { name: "Saint Joseph", state: "MI", stateName: "Michigan", population: 8289 },
  { name: "Trenton", state: "MI", stateName: "Michigan", population: 18253 },
  { name: "Ypsilanti", state: "MI", stateName: "Michigan", population: 20823 },

  // Minnesota
  { name: "Minneapolis", state: "MN", stateName: "Minnesota", population: 429954 },
  { name: "Saint Paul", state: "MN", stateName: "Minnesota", population: 311527 },
  { name: "Rochester", state: "MN", stateName: "Minnesota", population: 121395 },
  { name: "Duluth", state: "MN", stateName: "Minnesota", population: 86110 },
  { name: "Bloomington", state: "MN", stateName: "Minnesota", population: 89987 },
  { name: "Brooklyn Park", state: "MN", stateName: "Minnesota", population: 86078 },
  { name: "Plymouth", state: "MN", stateName: "Minnesota", population: 81462 },
  { name: "Saint Cloud", state: "MN", stateName: "Minnesota", population: 68961 },
  { name: "Eagan", state: "MN", stateName: "Minnesota", population: 68732 },
  { name: "Woodbury", state: "MN", stateName: "Minnesota", population: 75208 },
  { name: "Maple Grove", state: "MN", stateName: "Minnesota", population: 70018 },
  { name: "Eden Prairie", state: "MN", stateName: "Minnesota", population: 64098 },
  { name: "Minnetonka", state: "MN", stateName: "Minnesota", population: 53809 },
  { name: "Burnsville", state: "MN", stateName: "Minnesota", population: 64456 },
  { name: "Lakeville", state: "MN", stateName: "Minnesota", population: 69102 },
  { name: "Minnetonka", state: "MN", stateName: "Minnesota", population: 53809 },
  { name: "Apple Valley", state: "MN", stateName: "Minnesota", population: 55699 },
  { name: "Blaine", state: "MN", stateName: "Minnesota", population: 70178 },
  { name: "Brooklyn Center", state: "MN", stateName: "Minnesota", population: 33782 },
  { name: "Coon Rapids", state: "MN", stateName: "Minnesota", population: 63599 },
  { name: "Cottage Grove", state: "MN", stateName: "Minnesota", population: 38739 },
  { name: "Edina", state: "MN", stateName: "Minnesota", population: 53284 },
  { name: "Fridley", state: "MN", stateName: "Minnesota", population: 28184 },
  { name: "Inver Grove Heights", state: "MN", stateName: "Minnesota", population: 35278 },
  { name: "Mankato", state: "MN", stateName: "Minnesota", population: 44895 },
  { name: "Maplewood", state: "MN", stateName: "Minnesota", population: 40801 },
  { name: "Moorhead", state: "MN", stateName: "Minnesota", population: 44105 },
  { name: "Oakdale", state: "MN", stateName: "Minnesota", population: 28030 },
  { name: "Richfield", state: "MN", stateName: "Minnesota", population: 36421 },
  { name: "Roseville", state: "MN", stateName: "Minnesota", population: 36124 },
  { name: "Saint Louis Park", state: "MN", stateName: "Minnesota", population: 48723 },
  { name: "Savage", state: "MN", stateName: "Minnesota", population: 32183 },
  { name: "Shoreview", state: "MN", stateName: "Minnesota", population: 26921 },
  { name: "Vadnais Heights", state: "MN", stateName: "Minnesota", population: 12855 },
  { name: "White Bear Lake", state: "MN", stateName: "Minnesota", population: 25137 },
  { name: "Winona", state: "MN", stateName: "Minnesota", population: 26183 },
  { name: "Albert Lea", state: "MN", stateName: "Minnesota", population: 17899 },
  { name: "Alexandria", state: "MN", stateName: "Minnesota", population: 14335 },
  { name: "Austin", state: "MN", stateName: "Minnesota", population: 26356 },
  { name: "Bemidji", state: "MN", stateName: "Minnesota", population: 15405 },
  { name: "Brainerd", state: "MN", stateName: "Minnesota", population: 13682 },
  { name: "Crookston", state: "MN", stateName: "Minnesota", population: 7746 },
  { name: "Ely", state: "MN", stateName: "Minnesota", population: 3408 },
  { name: "Eveleth", state: "MN", stateName: "Minnesota", population: 3621 },
  { name: "Faribault", state: "MN", stateName: "Minnesota", population: 24535 },
  { name: "Fergus Falls", state: "MN", stateName: "Minnesota", population: 13682 },
  { name: "Hastings", state: "MN", stateName: "Minnesota", population: 22154 },
  { name: "Hibbing", state: "MN", stateName: "Minnesota", population: 16092 },
  { name: "International Falls", state: "MN", stateName: "Minnesota", population: 5888 },
  { name: "Little Falls", state: "MN", stateName: "Minnesota", population: 8743 },
  { name: "Mankato", state: "MN", stateName: "Minnesota", population: 44895 },
  { name: "Moorhead", state: "MN", stateName: "Minnesota", population: 44105 },
  { name: "New Ulm", state: "MN", stateName: "Minnesota", population: 13265 },
  { name: "Northfield", state: "MN", stateName: "Minnesota", population: 20663 },
  { name: "Owatonna", state: "MN", stateName: "Minnesota", population: 26223 },
  { name: "Pipestone", state: "MN", stateName: "Minnesota", population: 4157 },
  { name: "Red Wing", state: "MN", stateName: "Minnesota", population: 16529 },
  { name: "Rochester", state: "MN", stateName: "Minnesota", population: 121395 },
  { name: "Saint Cloud", state: "MN", stateName: "Minnesota", population: 68961 },
  { name: "Saint Paul", state: "MN", stateName: "Minnesota", population: 311527 },
  { name: "Sauk Centre", state: "MN", stateName: "Minnesota", population: 4457 },
  { name: "South Saint Paul", state: "MN", stateName: "Minnesota", population: 20559 },
  { name: "Stillwater", state: "MN", stateName: "Minnesota", population: 19471 },
  { name: "Virginia", state: "MN", stateName: "Minnesota", population: 8628 },
  { name: "Willmar", state: "MN", stateName: "Minnesota", population: 20946 },
  { name: "Winona", state: "MN", stateName: "Minnesota", population: 26183 },

  // Mississippi
  { name: "Jackson", state: "MS", stateName: "Mississippi", population: 153701 },
  { name: "Gulfport", state: "MS", stateName: "Mississippi", population: 71818 },
  { name: "Southaven", state: "MS", stateName: "Mississippi", population: 54437 },
  { name: "Hattiesburg", state: "MS", stateName: "Mississippi", population: 45589 },
  { name: "Biloxi", state: "MS", stateName: "Mississippi", population: 45968 },
  { name: "Meridian", state: "MS", stateName: "Mississippi", population: 35799 },
  { name: "Tupelo", state: "MS", stateName: "Mississippi", population: 38450 },
  { name: "Greenville", state: "MS", stateName: "Mississippi", population: 29797 },
  { name: "Olive Branch", state: "MS", stateName: "Mississippi", population: 39447 },
  { name: "Horn Lake", state: "MS", stateName: "Mississippi", population: 28362 },
  { name: "Clinton", state: "MS", stateName: "Mississippi", population: 24299 },
  { name: "Madison", state: "MS", stateName: "Mississippi", population: 27147 },
  { name: "Pearl", state: "MS", stateName: "Mississippi", population: 26400 },
  { name: "Ridgeland", state: "MS", stateName: "Mississippi", population: 24340 },
  { name: "Starkville", state: "MS", stateName: "Mississippi", population: 25546 },
  { name: "Columbus", state: "MS", stateName: "Mississippi", population: 23798 },
  { name: "Oxford", state: "MS", stateName: "Mississippi", population: 25916 },
  { name: "Vicksburg", state: "MS", stateName: "Mississippi", population: 22190 },
  { name: "Pascagoula", state: "MS", stateName: "Mississippi", population: 21926 },
  { name: "Laurel", state: "MS", stateName: "Mississippi", population: 17381 },
  { name: "Natchez", state: "MS", stateName: "Mississippi", population: 14918 },
  { name: "Greenwood", state: "MS", stateName: "Mississippi", population: 14089 },
  { name: "Clarksdale", state: "MS", stateName: "Mississippi", population: 15110 },
  { name: "Cleveland", state: "MS", stateName: "Mississippi", population: 11561 },
  { name: "Corinth", state: "MS", stateName: "Mississippi", population: 14773 },
  { name: "Grenada", state: "MS", stateName: "Mississippi", population: 12681 },
  { name: "Holly Springs", state: "MS", stateName: "Mississippi", population: 7769 },
  { name: "Kosciusko", state: "MS", stateName: "Mississippi", population: 7240 },
  { name: "McComb", state: "MS", stateName: "Mississippi", population: 12306 },
  { name: "Moss Point", state: "MS", stateName: "Mississippi", population: 12891 },
  { name: "Ocean Springs", state: "MS", stateName: "Mississippi", population: 17792 },
  { name: "Philadelphia", state: "MS", stateName: "Mississippi", population: 7299 },
  { name: "Port Gibson", state: "MS", stateName: "Mississippi", population: 1360 },
  { name: "Yazoo City", state: "MS", stateName: "Mississippi", population: 10871 },

  // Missouri
  { name: "Kansas City", state: "MO", stateName: "Missouri", population: 508090 },
  { name: "Saint Louis", state: "MO", stateName: "Missouri", population: 301578 },
  { name: "Springfield", state: "MO", stateName: "Missouri", population: 169176 },
  { name: "Columbia", state: "MO", stateName: "Missouri", population: 126254 },
  { name: "Independence", state: "MO", stateName: "Missouri", population: 123011 },
  { name: "Lee's Summit", state: "MO", stateName: "Missouri", population: 101108 },
  { name: "O'Fallon", state: "MO", stateName: "Missouri", population: 91316 },
  { name: "Saint Joseph", state: "MO", stateName: "Missouri", population: 72808 },
  { name: "Saint Charles", state: "MO", stateName: "Missouri", population: 70648 },
  { name: "Saint Peters", state: "MO", stateName: "Missouri", population: 57631 },
  { name: "Blue Springs", state: "MO", stateName: "Missouri", population: 58394 },
  { name: "Florissant", state: "MO", stateName: "Missouri", population: 49893 },
  { name: "Joplin", state: "MO", stateName: "Missouri", population: 51551 },
  { name: "Chesterfield", state: "MO", stateName: "Missouri", population: 49324 },
  { name: "Jefferson City", state: "MO", stateName: "Missouri", population: 43088 },
  { name: "Cape Girardeau", state: "MO", stateName: "Missouri", population: 40179 },
  { name: "Oakville", state: "MO", stateName: "Missouri", population: 36143 },
  { name: "Wildwood", state: "MO", stateName: "Missouri", population: 35417 },
  { name: "University City", state: "MO", stateName: "Missouri", population: 35065 },
  { name: "Liberty", state: "MO", stateName: "Missouri", population: 30867 },
  { name: "Ballwin", state: "MO", stateName: "Missouri", population: 30308 },
  { name: "Raytown", state: "MO", stateName: "Missouri", population: 29638 },
  { name: "Gladstone", state: "MO", stateName: "Missouri", population: 26729 },
  { name: "Grandview", state: "MO", stateName: "Missouri", population: 24747 },
  { name: "Hazelwood", state: "MO", stateName: "Missouri", population: 25103 },
  { name: "Kirkwood", state: "MO", stateName: "Missouri", population: 27640 },
  { name: "Maryland Heights", state: "MO", stateName: "Missouri", population: 27715 },
  { name: "Nixa", state: "MO", stateName: "Missouri", population: 23182 },
  { name: "Ozark", state: "MO", stateName: "Missouri", population: 20795 },
  { name: "Republic", state: "MO", stateName: "Missouri", population: 16698 },
  { name: "Sedalia", state: "MO", stateName: "Missouri", population: 21229 },
  { name: "Sikeston", state: "MO", stateName: "Missouri", population: 16020 },
  { name: "Warrensburg", state: "MO", stateName: "Missouri", population: 19766 },
  { name: "Webb City", state: "MO", stateName: "Missouri", population: 10996 },
  { name: "West Plains", state: "MO", stateName: "Missouri", population: 12177 },
  { name: "Excelsior Springs", state: "MO", stateName: "Missouri", population: 11284 },
  { name: "Hannibal", state: "MO", stateName: "Missouri", population: 17191 },
  { name: "Marshall", state: "MO", stateName: "Missouri", population: 13005 },
  { name: "Mexico", state: "MO", stateName: "Missouri", population: 11443 },
  { name: "Neosho", state: "MO", stateName: "Missouri", population: 12418 },
  { name: "Poplar Bluff", state: "MO", stateName: "Missouri", population: 16914 },
  { name: "Rolla", state: "MO", stateName: "Missouri", population: 19559 },
  { name: "Sainte Genevieve", state: "MO", stateName: "Missouri", population: 4420 },
  { name: "Salem", state: "MO", stateName: "Missouri", population: 4957 },
  { name: "Sullivan", state: "MO", stateName: "Missouri", population: 6981 },
  { name: "Union", state: "MO", stateName: "Missouri", population: 12204 },
  { name: "Washington", state: "MO", stateName: "Missouri", population: 14274 },
  { name: "Boonville", state: "MO", stateName: "Missouri", population: 8301 },
  { name: "Branson", state: "MO", stateName: "Missouri", population: 12194 },
  { name: "Carthage", state: "MO", stateName: "Missouri", population: 14902 },
  { name: "Chillicothe", state: "MO", stateName: "Missouri", population: 9020 },
  { name: "Clayton", state: "MO", stateName: "Missouri", population: 16795 },
  { name: "Ferguson", state: "MO", stateName: "Missouri", population: 20618 },
  { name: "Fulton", state: "MO", stateName: "Missouri", population: 12690 },
  { name: "Kirksville", state: "MO", stateName: "Missouri", population: 17447 },
  { name: "Lamar", state: "MO", stateName: "Missouri", population: 4266 },
  { name: "Lebanon", state: "MO", stateName: "Missouri", population: 14474 },
  { name: "Lexington", state: "MO", stateName: "Missouri", population: 4364 },
  { name: "Maryville", state: "MO", stateName: "Missouri", population: 11972 },
  { name: "Monett", state: "MO", stateName: "Missouri", population: 8887 },
  { name: "New Madrid", state: "MO", stateName: "Missouri", population: 2855 },
  { name: "Parkville", state: "MO", stateName: "Missouri", population: 6599 },
  { name: "Riverside", state: "MO", stateName: "Missouri", population: 3208 },
  { name: "Saint Charles", state: "MO", stateName: "Missouri", population: 70648 },
  { name: "Saint Joseph", state: "MO", stateName: "Missouri", population: 72808 },
  { name: "Saint Louis", state: "MO", stateName: "Missouri", population: 301578 },
  { name: "Sainte Genevieve", state: "MO", stateName: "Missouri", population: 4420 },
  { name: "Sedalia", state: "MO", stateName: "Missouri", population: 21229 },
  { name: "Sikeston", state: "MO", stateName: "Missouri", population: 16020 },
  { name: "Springfield", state: "MO", stateName: "Missouri", population: 169176 },
  { name: "Warrensburg", state: "MO", stateName: "Missouri", population: 19766 },
  { name: "West Plains", state: "MO", stateName: "Missouri", population: 12177 },
  { name: "Boonville", state: "MO", stateName: "Missouri", population: 8301 },
  { name: "Branson", state: "MO", stateName: "Missouri", population: 12194 },
  { name: "Cape Girardeau", state: "MO", stateName: "Missouri", population: 40179 },
  { name: "Carthage", state: "MO", stateName: "Missouri", population: 14902 },
  { name: "Chillicothe", state: "MO", stateName: "Missouri", population: 9020 },
  { name: "Clayton", state: "MO", stateName: "Missouri", population: 16795 },
  { name: "Columbia", state: "MO", stateName: "Missouri", population: 126254 },
  { name: "Excelsior Springs", state: "MO", stateName: "Missouri", population: 11284 },
  { name: "Ferguson", state: "MO", stateName: "Missouri", population: 20618 },
  { name: "Fulton", state: "MO", stateName: "Missouri", population: 12690 },
  { name: "Hannibal", state: "MO", stateName: "Missouri", population: 17191 },
  { name: "Independence", state: "MO", stateName: "Missouri", population: 123011 },
  { name: "Jefferson City", state: "MO", stateName: "Missouri", population: 43088 },
  { name: "Joplin", state: "MO", stateName: "Missouri", population: 51551 },
  { name: "Kansas City", state: "MO", stateName: "Missouri", population: 508090 },
  { name: "Kirksville", state: "MO", stateName: "Missouri", population: 17447 },
  { name: "Lamar", state: "MO", stateName: "Missouri", population: 4266 },
  { name: "Lebanon", state: "MO", stateName: "Missouri", population: 14474 },
  { name: "Lexington", state: "MO", stateName: "Missouri", population: 4364 },
  { name: "Marshall", state: "MO", stateName: "Missouri", population: 13005 },
  { name: "Maryville", state: "MO", stateName: "Missouri", population: 11972 },
  { name: "Mexico", state: "MO", stateName: "Missouri", population: 11443 },
  { name: "Monett", state: "MO", stateName: "Missouri", population: 8887 },
  { name: "Neosho", state: "MO", stateName: "Missouri", population: 12418 },
  { name: "New Madrid", state: "MO", stateName: "Missouri", population: 2855 },
  { name: "Poplar Bluff", state: "MO", stateName: "Missouri", population: 16914 },
  { name: "Rolla", state: "MO", stateName: "Missouri", population: 19559 },
  { name: "Sainte Genevieve", state: "MO", stateName: "Missouri", population: 4420 },
  { name: "Salem", state: "MO", stateName: "Missouri", population: 4957 },
  { name: "Sedalia", state: "MO", stateName: "Missouri", population: 21229 },
  { name: "Sikeston", state: "MO", stateName: "Missouri", population: 16020 },
  { name: "Springfield", state: "MO", stateName: "Missouri", population: 169176 },
  { name: "Sullivan", state: "MO", stateName: "Missouri", population: 6981 },
  { name: "Union", state: "MO", stateName: "Missouri", population: 12204 },
  { name: "Warrensburg", state: "MO", stateName: "Missouri", population: 19766 },
  { name: "Washington", state: "MO", stateName: "Missouri", population: 14274 },
  { name: "West Plains", state: "MO", stateName: "Missouri", population: 12177 },

  // Montana
  { name: "Billings", state: "MT", stateName: "Montana", population: 117116 },
  { name: "Missoula", state: "MT", stateName: "Montana", population: 73749 },
  { name: "Great Falls", state: "MT", stateName: "Montana", population: 60001 },
  { name: "Bozeman", state: "MT", stateName: "Montana", population: 53532 },
  { name: "Butte", state: "MT", stateName: "Montana", population: 35552 },
  { name: "Helena", state: "MT", stateName: "Montana", population: 32891 },
  { name: "Kalispell", state: "MT", stateName: "Montana", population: 24800 },
  { name: "Havre", state: "MT", stateName: "Montana", population: 9817 },
  { name: "Anaconda", state: "MT", stateName: "Montana", population: 9142 },
  { name: "Miles City", state: "MT", stateName: "Montana", population: 8371 },
  { name: "Belt", state: "MT", stateName: "Montana", population: 597 },
  { name: "Bigfork", state: "MT", stateName: "Montana", population: 4216 },
  { name: "Boulder", state: "MT", stateName: "Montana", population: 1195 },
  { name: "Browning", state: "MT", stateName: "Montana", population: 1018 },
  { name: "Butte", state: "MT", stateName: "Montana", population: 35552 },
  { name: "Chester", state: "MT", stateName: "Montana", population: 847 },
  { name: "Chinook", state: "MT", stateName: "Montana", population: 1203 },
  { name: "Choteau", state: "MT", stateName: "Montana", population: 1684 },
  { name: "Circle", state: "MT", stateName: "Montana", population: 644 },
  { name: "Colstrip", state: "MT", stateName: "Montana", population: 2214 },
  { name: "Columbia Falls", state: "MT", stateName: "Montana", population: 5295 },
  { name: "Columbus", state: "MT", stateName: "Montana", population: 1897 },
  { name: "Conrad", state: "MT", stateName: "Montana", population: 2570 },
  { name: "Cut Bank", state: "MT", stateName: "Montana", population: 3048 },
  { name: "Deer Lodge", state: "MT", stateName: "Montana", population: 2898 },
  { name: "Dillon", state: "MT", stateName: "Montana", population: 4132 },
  { name: "Ekalaka", state: "MT", stateName: "Montana", population: 399 },
  { name: "Fort Benton", state: "MT", stateName: "Montana", population: 1501 },
  { name: "Fort Peck", state: "MT", stateName: "Montana", population: 0 },
  { name: "Glasgow", state: "MT", stateName: "Montana", population: 3226 },
  { name: "Glendive", state: "MT", stateName: "Montana", population: 4935 },
  { name: "Hamilton", state: "MT", stateName: "Montana", population: 4680 },
  { name: "Hardin", state: "MT", stateName: "Montana", population: 3666 },
  { name: "Harlowton", state: "MT", stateName: "Montana", population: 955 },
  { name: "Harlem", state: "MT", stateName: "Montana", population: 808 },
  { name: "Havre", state: "MT", stateName: "Montana", population: 9817 },
  { name: "Helena", state: "MT", stateName: "Montana", population: 32891 },
  { name: "Huntley", state: "MT", stateName: "Montana", population: 446 },
  { name: "Hysham", state: "MT", stateName: "Montana", population: 312 },
  { name: "Jordan", state: "MT", stateName: "Montana", population: 343 },
  { name: "Kalispell", state: "MT", stateName: "Montana", population: 24800 },
  { name: "Laurel", state: "MT", stateName: "Montana", population: 7181 },
  { name: "Lewistown", state: "MT", stateName: "Montana", population: 5904 },
  { name: "Libby", state: "MT", stateName: "Montana", population: 2628 },
  { name: "Livingston", state: "MT", stateName: "Montana", population: 7580 },
  { name: "Malta", state: "MT", stateName: "Montana", population: 1830 },
  { name: "Miles City", state: "MT", stateName: "Montana", population: 8371 },
  { name: "Missoula", state: "MT", stateName: "Montana", population: 73749 },
  { name: "Plentywood", state: "MT", stateName: "Montana", population: 1734 },
  { name: "Polson", state: "MT", stateName: "Montana", population: 5037 },
  { name: "Red Lodge", state: "MT", stateName: "Montana", population: 2125 },
  { name: "Ronan", state: "MT", stateName: "Montana", population: 1871 },
  { name: "Roundup", state: "MT", stateName: "Montana", population: 1788 },
  { name: "Scobey", state: "MT", stateName: "Montana", population: 1017 },
  { name: "Shelby", state: "MT", stateName: "Montana", population: 3042 },
  { name: "Sidney", state: "MT", stateName: "Montana", population: 6406 },
  { name: "Stevensville", state: "MT", stateName: "Montana", population: 2189 },
  { name: "Thompson Falls", state: "MT", stateName: "Montana", population: 1313 },
  { name: "Three Forks", state: "MT", stateName: "Montana", population: 1869 },
  { name: "Townsend", state: "MT", stateName: "Montana", population: 1878 },
  { name: "Virginia City", state: "MT", stateName: "Montana", population: 190 },
  { name: "Whitefish", state: "MT", stateName: "Montana", population: 8080 },
  { name: "Whitehall", state: "MT", stateName: "Montana", population: 1038 },
  { name: "Wolf Point", state: "MT", stateName: "Montana", population: 2621 },

  // Nebraska
  { name: "Omaha", state: "NE", stateName: "Nebraska", population: 486051 },
  { name: "Lincoln", state: "NE", stateName: "Nebraska", population: 291082 },
  { name: "Bellevue", state: "NE", stateName: "Nebraska", population: 64176 },
  { name: "Grand Island", state: "NE", stateName: "Nebraska", population: 53099 },
  { name: "Kearney", state: "NE", stateName: "Nebraska", population: 33650 },
  { name: "Fremont", state: "NE", stateName: "Nebraska", population: 26160 },
  { name: "Hastings", state: "NE", stateName: "Nebraska", population: 24952 },
  { name: "North Platte", state: "NE", stateName: "Nebraska", population: 23390 },
  { name: "Norfolk", state: "NE", stateName: "Nebraska", population: 24480 },
  { name: "Columbus", state: "NE", stateName: "Nebraska", population: 23295 },
  { name: "Papillion", state: "NE", stateName: "Nebraska", population: 24200 },
  { name: "La Vista", state: "NE", stateName: "Nebraska", population: 17594 },
  { name: "Scottsbluff", state: "NE", stateName: "Nebraska", population: 14659 },
  { name: "South Sioux City", state: "NE", stateName: "Nebraska", population: 13634 },
  { name: "Beatrice", state: "NE", stateName: "Nebraska", population: 12261 },
  { name: "Chalco", state: "NE", stateName: "Nebraska", population: 10894 },
  { name: "McCook", state: "NE", stateName: "Nebraska", population: 7680 },
  { name: "Alliance", state: "NE", stateName: "Nebraska", population: 8211 },
  { name: "York", state: "NE", stateName: "Nebraska", population: 8066 },
  { name: "Sidney", state: "NE", stateName: "Nebraska", population: 6757 },
  { name: "Blair", state: "NE", stateName: "Nebraska", population: 7939 },
  { name: "Seward", state: "NE", stateName: "Nebraska", population: 7519 },
  { name: "Gering", state: "NE", stateName: "Nebraska", population: 8446 },
  { name: "Nebraska City", state: "NE", stateName: "Nebraska", population: 7259 },
  { name: "Plattsmouth", state: "NE", stateName: "Nebraska", population: 6480 },
  { name: "Crete", state: "NE", stateName: "Nebraska", population: 6968 },
  { name: "Wahoo", state: "NE", stateName: "Nebraska", population: 4508 },
  { name: "Holdrege", state: "NE", stateName: "Nebraska", population: 5495 },
  { name: "Lexington", state: "NE", stateName: "Nebraska", population: 10230 },
  { name: "Broken Bow", state: "NE", stateName: "Nebraska", population: 3495 },
  { name: "Chadron", state: "NE", stateName: "Nebraska", population: 5439 },
  { name: "Central City", state: "NE", stateName: "Nebraska", population: 2945 },
  { name: "Auburn", state: "NE", stateName: "Nebraska", population: 3460 },
  { name: "Fairbury", state: "NE", stateName: "Nebraska", population: 3839 },
  { name: "Falls City", state: "NE", stateName: "Nebraska", population: 4160 },
  { name: "Fremont", state: "NE", stateName: "Nebraska", population: 26160 },
  { name: "Gothenburg", state: "NE", stateName: "Nebraska", population: 3583 },
  { name: "Grand Island", state: "NE", stateName: "Nebraska", population: 53099 },
  { name: "Hastings", state: "NE", stateName: "Nebraska", population: 24952 },
  { name: "Kearney", state: "NE", stateName: "Nebraska", population: 33650 },
  { name: "Lincoln", state: "NE", stateName: "Nebraska", population: 291082 },
  { name: "McCook", state: "NE", stateName: "Nebraska", population: 7680 },
  { name: "Nebraska City", state: "NE", stateName: "Nebraska", population: 7259 },
  { name: "Norfolk", state: "NE", stateName: "Nebraska", population: 24480 },
  { name: "North Platte", state: "NE", stateName: "Nebraska", population: 23390 },
  { name: "Omaha", state: "NE", stateName: "Nebraska", population: 486051 },
  { name: "Papillion", state: "NE", stateName: "Nebraska", population: 24200 },
  { name: "Plattsmouth", state: "NE", stateName: "Nebraska", population: 6480 },
  { name: "Red Cloud", state: "NE", stateName: "Nebraska", population: 1022 },
  { name: "Scottsbluff", state: "NE", stateName: "Nebraska", population: 14659 },
  { name: "Seward", state: "NE", stateName: "Nebraska", population: 7519 },
  { name: "Sidney", state: "NE", stateName: "Nebraska", population: 6757 },
  { name: "South Sioux City", state: "NE", stateName: "Nebraska", population: 13634 },
  { name: "Superior", state: "NE", stateName: "Nebraska", population: 1828 },
  { name: "Tekamah", state: "NE", stateName: "Nebraska", population: 1736 },
  { name: "Wahoo", state: "NE", stateName: "Nebraska", population: 4508 },
  { name: "York", state: "NE", stateName: "Nebraska", population: 8066 },

  // Nevada
  { name: "Las Vegas", state: "NV", stateName: "Nevada", population: 641903 },
  { name: "Henderson", state: "NV", stateName: "Nevada", population: 317610 },
  { name: "Reno", state: "NV", stateName: "Nevada", population: 264165 },
  { name: "North Las Vegas", state: "NV", stateName: "Nevada", population: 262527 },
  { name: "Sparks", state: "NV", stateName: "Nevada", population: 108445 },
  { name: "Carson City", state: "NV", stateName: "Nevada", population: 58275 },
  { name: "Fernley", state: "NV", stateName: "Nevada", population: 22095 },
  { name: "Elko", state: "NV", stateName: "Nevada", population: 20707 },
  { name: "Mesquite", state: "NV", stateName: "Nevada", population: 19107 },
  { name: "Boulder City", state: "NV", stateName: "Nevada", population: 16206 },
  { name: "Fallon", state: "NV", stateName: "Nevada", population: 8610 },
  { name: "Winnemucca", state: "NV", stateName: "Nevada", population: 8267 },
  { name: "West Wendover", state: "NV", stateName: "Nevada", population: 4441 },
  { name: "Ely", state: "NV", stateName: "Nevada", population: 4048 },
  { name: "Yerington", state: "NV", stateName: "Nevada", population: 3198 },
  { name: "Caliente", state: "NV", stateName: "Nevada", population: 1028 },
  { name: "Carlin", state: "NV", stateName: "Nevada", population: 2185 },
  { name: "Eureka", state: "NV", stateName: "Nevada", population: 610 },
  { name: "Gabbs", state: "NV", stateName: "Nevada", population: 269 },
  { name: "Goldfield", state: "NV", stateName: "Nevada", population: 268 },
  { name: "Hawthorne", state: "NV", stateName: "Nevada", population: 3241 },
  { name: "Lovelock", state: "NV", stateName: "Nevada", population: 1905 },
  { name: "McDermitt", state: "NV", stateName: "Nevada", population: 513 },
  { name: "Pioche", state: "NV", stateName: "Nevada", population: 1002 },
  { name: "Reno", state: "NV", stateName: "Nevada", population: 264165 },
  { name: "Tonopah", state: "NV", stateName: "Nevada", population: 2478 },
  { name: "Virginia City", state: "NV", stateName: "Nevada", population: 855 },
  { name: "Wells", state: "NV", stateName: "Nevada", population: 1292 },

  // New Hampshire
  { name: "Manchester", state: "NH", stateName: "New Hampshire", population: 115644 },
  { name: "Nashua", state: "NH", stateName: "New Hampshire", population: 89355 },
  { name: "Concord", state: "NH", stateName: "New Hampshire", population: 43627 },
  { name: "Derry", state: "NH", stateName: "New Hampshire", population: 34579 },
  { name: "Dover", state: "NH", stateName: "New Hampshire", population: 32154 },
  { name: "Rochester", state: "NH", stateName: "New Hampshire", population: 32105 },
  { name: "Salem", state: "NH", stateName: "New Hampshire", population: 29892 },
  { name: "Keene", state: "NH", stateName: "New Hampshire", population: 23152 },
  { name: "Londonderry", state: "NH", stateName: "New Hampshire", population: 25597 },
  { name: "Hudson", state: "NH", stateName: "New Hampshire", population: 25478 },
  { name: "Bedford", state: "NH", stateName: "New Hampshire", population: 22274 },
  { name: "Goffstown", state: "NH", stateName: "New Hampshire", population: 18324 },
  { name: "Portsmouth", state: "NH", stateName: "New Hampshire", population: 21756 },
  { name: "Laconia", state: "NH", stateName: "New Hampshire", population: 16671 },
  { name: "Hampton", state: "NH", stateName: "New Hampshire", population: 16136 },
  { name: "Milford", state: "NH", stateName: "New Hampshire", population: 15772 },
  { name: "Durham", state: "NH", stateName: "New Hampshire", population: 15720 },
  { name: "Exeter", state: "NH", stateName: "New Hampshire", population: 14906 },
  { name: "Hooksett", state: "NH", stateName: "New Hampshire", population: 14504 },
  { name: "Pelham", state: "NH", stateName: "New Hampshire", population: 13678 },
  { name: "Windham", state: "NH", stateName: "New Hampshire", population: 13592 },
  { name: "Merrimack", state: "NH", stateName: "New Hampshire", population: 25727 },
  { name: "Hollis", state: "NH", stateName: "New Hampshire", population: 8151 },
  { name: "Amherst", state: "NH", stateName: "New Hampshire", population: 11541 },
  { name: "Bow", state: "NH", stateName: "New Hampshire", population: 5786 },
  { name: "Hollis", state: "NH", stateName: "New Hampshire", population: 8151 },
  { name: "Litchfield", state: "NH", stateName: "New Hampshire", population: 8512 },
  { name: "New Ipswich", state: "NH", stateName: "New Hampshire", population: 5234 },
  { name: "Peterborough", state: "NH", stateName: "New Hampshire", population: 6318 },
  { name: "Plymouth", state: "NH", stateName: "New Hampshire", population: 6198 },
  { name: "Berlin", state: "NH", stateName: "New Hampshire", population: 10151 },
  { name: "Claremont", state: "NH", stateName: "New Hampshire", population: 12902 },
  { name: "Franklin", state: "NH", stateName: "New Hampshire", population: 8717 },
  { name: "Lebanon", state: "NH", stateName: "New Hampshire", population: 14006 },
  { name: "Newport", state: "NH", stateName: "New Hampshire", population: 4355 }
];

module.exports = remainingCities;
