name: Discovery Feed Test

on:
  workflow_dispatch:

jobs:
  discovery-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd holler-discovery
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Test database connection
      env:
        DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
      run: |
        cd holler-discovery
        python -c "
        import asyncio
        from src.db import db
        async def test_db():
            try:
                await db.connect()
                print('Database connection successful')
                await db.disconnect()
            except Exception as e:
                print(f'Database connection failed: {e}')
        asyncio.run(test_db())
        "
    
    - name: Test HTML generation
      env:
        DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
        LINKS_PER_PAGE: 200
        BASE_URL: https://holler.news
      run: |
        cd holler-discovery
        python -c "
        from src.pipeline.html_writer import HTMLWriter
        writer = HTMLWriter(output_dir='../client/build')
        print('HTMLWriter created successfully')
        print(f'Output directory: {writer.output_dir}')
        print(f'Template directory: {writer.template_dir}')
        "
    
    - name: Test sitemap generation
      env:
        DATABASE_URL: ${{ secrets.RAILWAY_DATABASE_URL }}
        BASE_URL: https://holler.news
        SITEMAP_URLS_PER_FILE: 50000
      run: |
        cd holler-discovery
        python -c "
        from src.pipeline.sitemap_writer import SitemapWriter
        writer = SitemapWriter(output_dir='../client/build', base_url='https://holler.news')
        print('SitemapWriter created successfully')
        print(f'Output directory: {writer.output_dir}')
        print(f'Sitemaps directory: {writer.sitemaps_dir}')
        "