name: Discovery Simple Test

on:
  workflow_dispatch:

jobs:
  discovery-simple-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd holler-discovery
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    
    - name: Create test discovery files
      run: |
        cd holler-discovery
        python -c "
        import os
        from pathlib import Path
        
        # Create test discovery directory
        output_dir = Path('../client/build/discover/2024-01-05')
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create a simple test page
        test_html = '''<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>Discovery Feed Test - 2024-01-05</title>
</head>
<body>
    <h1>Discovery Feed Test</h1>
    <p>This is a test discovery page generated by GitHub Actions.</p>
    <p>Date: 2024-01-05</p>
    <ul>
        <li><a href=\"https://example.com/test1\">Test URL 1</a></li>
        <li><a href=\"https://example.com/test2\">Test URL 2</a></li>
        <li><a href=\"https://example.com/test3\">Test URL 3</a></li>
    </ul>
</body>
</html>'''
        
        # Write test files
        (output_dir / 'index.html').write_text(test_html)
        (output_dir / 'page-000001.html').write_text(test_html)
        
        print(f'Created test files in {output_dir}')
        print(f'Files created: {list(output_dir.iterdir())}')
        "
    
    - name: Commit test files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add client/build/discover/
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add test discovery feed files"
          git push origin main
          echo "Test files committed and pushed"
        fi
